// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package variablelibrary

// CreateVariableLibraryRequest - Create VariableLibrary request payload.
type CreateVariableLibraryRequest struct {
	// REQUIRED; The VariableLibrary display name. The display name must follow naming rules according to item type.
	DisplayName *string

	// The VariableLibrary public definition.
	Definition *PublicDefinition

	// The VariableLibrary description. Maximum length is 256 characters.
	Description *string
}

// DefinitionResponse - VariableLibrary public definition response.
type DefinitionResponse struct {
	// READ-ONLY; VariableLibrary public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/variable-library-definition]
	// for more details on how to craft a VariableLibrary
	// public definition.
	Definition *PublicDefinition
}

// Properties - The VariableLibrary properties.
type Properties struct {
	// REQUIRED; The VariableLibrary current active value set.
	ActiveValueSetName *string
}

// PublicDefinition - VariableLibrary public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/variable-library-definition]
// for more details on how to craft a VariableLibrary
// public definition.
type PublicDefinition struct {
	// REQUIRED; A list of definition parts.
	Parts []PublicDefinitionPart

	// The format of the item definition. Supported format: VariableLibraryV1.
	Format *string
}

// PublicDefinitionPart - VariableLibrary definition part object.
type PublicDefinitionPart struct {
	// REQUIRED; The VariableLibrary public definition part path.
	Path *string

	// REQUIRED; The VariableLibrary public definition part payload.
	Payload *string

	// REQUIRED; The payload type.
	PayloadType *PayloadType
}

// UpdateVariableLibraryDefinitionRequest - Update VariableLibrary public definition request payload.
type UpdateVariableLibraryDefinitionRequest struct {
	// REQUIRED; VariableLibrary public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/variable-library-definition]
	// for more details on how to craft a VariableLibrary
	// public definition.
	Definition *PublicDefinition
}

// UpdateVariableLibraryRequest - Update VariableLibrary request.
type UpdateVariableLibraryRequest struct {
	// The VariableLibrary description. Maximum length is 256 characters.
	Description *string

	// The VariableLibrary display name. The display name must follow naming rules according to item type.
	DisplayName *string

	// The VariableLibrary properties.
	Properties *Properties
}

// VariableLibraries - A list of VariableLibraries.
type VariableLibraries struct {
	// REQUIRED; A list of VariableLibraries.
	Value []VariableLibrary

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// VariableLibrary - A VariableLibrary object.
type VariableLibrary struct {
	// REQUIRED; The item type.
	Type *ItemType

	// The item description.
	Description *string

	// The item display name.
	DisplayName *string

	// The VariableLibrary properties.
	Properties *Properties

	// READ-ONLY; The folder ID.
	FolderID *string

	// READ-ONLY; The item ID.
	ID *string

	// READ-ONLY; The workspace ID.
	WorkspaceID *string
}
