// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package sqldatabase

import "time"

// AuditSettings - The current state of audit settings for a database.
type AuditSettings struct {
	// REQUIRED; Audit actions and groups.
	AuditActionsAndGroups []string

	// REQUIRED; The predicate expression used to filter audit logs.
	PredicateExpression *string

	// REQUIRED; Retention days. 0 indicates indefinite retention period.
	RetentionDays *int32

	// REQUIRED; Audit settings state type.
	State *SQLAuditSettingsState

	// REQUIRED; The storage endpoint where audit logs are stored.
	StorageEndpoint *string
}

// AuditSettingsUpdate - Database audit settings update request.
type AuditSettingsUpdate struct {
	// Audit actions and groups. For the first time, when state is set to Enabled and this property is not provided, default audit
	// actions and groups will be applied.
	AuditActionsAndGroups []string

	// The predicate expression used to filter audit logs. For the first time, when state is set to Enabled and this property
	// is not provided, no predicate expression will be applied by default.
	PredicateExpression *string

	// Retention days. For the first time, when state is set to Enabled and this property is not provided, retentionDays will
	// be set to 0 (indefinite retention period) by default.
	RetentionDays *int32

	// Audit settings state type.
	State *SQLAuditSettingsState
}

// CreateSQLDatabaseRequest - Create SQL database request payload.
type CreateSQLDatabaseRequest struct {
	// REQUIRED; The SQL database display name. The display name must follow naming rules according to item type.
	DisplayName *string

	// The SQL database creation payload.
	CreationPayload CreationPayloadClassification

	// The SQL database definition.
	Definition *Definition

	// The SQL database description. Maximum length is 256 characters.
	Description *string

	// The folder ID. If not specified or null, the SQL database is created with the workspace as its folder.
	FolderID *string

	// The sensitivity label settings for the SQL database.
	SensitivityLabelSettings *SensitivityLabelSettings
}

// CreationPayload - SQL database item payload.
type CreationPayload struct {
	// REQUIRED; The creation mode of the SQL database creation.
	CreationMode *CreationMode
}

// GetCreationPayload implements the CreationPayloadClassification interface for type CreationPayload.
func (c *CreationPayload) GetCreationPayload() *CreationPayload { return c }

// Definition - The SQL database public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/sql-database-definition]
// for more details on the structure of the SQL database
// definition.
type Definition struct {
	// REQUIRED; A list of definition parts.
	Parts []PublicDefinitionPart

	// The format of the SQL database definition. Supported format: dacpac and sqlproj. If no format is provided, dacpac is used.
	Format *string
}

// DefinitionResponse - The SQL database public definition response.
type DefinitionResponse struct {
	// READ-ONLY; The SQL database public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/sql-database-definition]
	// for more details on the structure of the SQL database
	// definition.
	Definition *Definition
}

// EntireTenantPrincipal - Represents a tenant principal
type EntireTenantPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type EntireTenantPrincipal.
func (e *EntireTenantPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: e.DisplayName,
		ID:          e.ID,
		Type:        e.Type,
	}
}

// GroupPrincipal - Represents a security group.
type GroupPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Group specific details. Applicable when the principal type is Group.
	GroupDetails *GroupPrincipalGroupDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type GroupPrincipal.
func (g *GroupPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: g.DisplayName,
		ID:          g.ID,
		Type:        g.Type,
	}
}

// GroupPrincipalGroupDetails - Group specific details. Applicable when the principal type is Group.
type GroupPrincipalGroupDetails struct {
	// The type of the group. Additional group types may be added over time.
	GroupType *GroupType
}

// ItemReference - An item reference object.
type ItemReference struct {
	// REQUIRED; The item reference type.
	ReferenceType *ItemReferenceType
}

// GetItemReference implements the ItemReferenceClassification interface for type ItemReference.
func (i *ItemReference) GetItemReference() *ItemReference { return i }

// ItemReferenceByID - An item reference by ID object.
type ItemReferenceByID struct {
	// REQUIRED; The ID of the item.
	ItemID *string

	// REQUIRED; The item reference type.
	ReferenceType *ItemReferenceType

	// REQUIRED; The workspace ID of the item.
	WorkspaceID *string
}

// GetItemReference implements the ItemReferenceClassification interface for type ItemReferenceByID.
func (i *ItemReferenceByID) GetItemReference() *ItemReference {
	return &ItemReference{
		ReferenceType: i.ReferenceType,
	}
}

// ItemReferenceByVariable - An item reference by variable.
type ItemReferenceByVariable struct {
	// REQUIRED; The item reference type.
	ReferenceType *ItemReferenceType

	// REQUIRED; A variable reference string that specifies the Variable Library and the variable name inside it. Format: $(/**/_VarLibrary_/_VarName_)
	// for a Variable Library named VarLibrary and a variable named
	// VarName.
	VariableReference *string
}

// GetItemReference implements the ItemReferenceClassification interface for type ItemReferenceByVariable.
func (i *ItemReferenceByVariable) GetItemReference() *ItemReference {
	return &ItemReference{
		ReferenceType: i.ReferenceType,
	}
}

// ItemTag - Represents a tag applied on an item.
type ItemTag struct {
	// REQUIRED; The name of the tag.
	DisplayName *string

	// REQUIRED; The tag ID.
	ID *string
}

// NewSQLDatabaseCreationPayload - Create a SQL database item creation payload with supported settings
type NewSQLDatabaseCreationPayload struct {
	// REQUIRED; The creation mode of the SQL database creation.
	CreationMode *CreationMode

	// Set the backup retention period in days. The minimum is 1 days. The maximum is 35 days.
	BackupRetentionDays *int32

	// Set the collation of the SQL database.
	Collation *string
}

// GetCreationPayload implements the CreationPayloadClassification interface for type NewSQLDatabaseCreationPayload.
func (n *NewSQLDatabaseCreationPayload) GetCreationPayload() *CreationPayload {
	return &CreationPayload{
		CreationMode: n.CreationMode,
	}
}

// Principal - Represents an identity or a Microsoft Entra group.
type Principal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type Principal.
func (p *Principal) GetPrincipal() *Principal { return p }

// Properties - The SQL database properties.
type Properties struct {
	// REQUIRED; The connection string of the database.
	ConnectionString *string

	// REQUIRED; The database name.
	DatabaseName *string

	// REQUIRED; The server fully qualified domain name (FQDN).
	ServerFqdn *string

	// The backup retention period in days.
	BackupRetentionDays *int32

	// The collation of the SQL database.
	Collation *string

	// ISO 8601 timestamp for the earliest restore point of the database in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	EarliestRestorePoint *time.Time

	// ISO 8601 timestamp for the latest restore point of the database in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	LatestRestorePoint *time.Time
}

// PublicDefinitionPart - SQL database definition part object.
type PublicDefinitionPart struct {
	// The SQL database public definition part path. Supported SQL database content extensions: .dacpac for dacpac format; .sqlproj,
	// .sql for sqlproj format.
	Path *string

	// The SQL database public definition part payload.
	Payload *string

	// The payload type.
	PayloadType *PayloadType
}

// RestorableDeletedSQLDatabase - A restorable deleted SQL database object.
type RestorableDeletedSQLDatabase struct {
	// The Fabric display name of the restorable deleted SQL database.
	DisplayName *string

	// The restorable deleted SQL database properties.
	Properties *RestorableDeletedSQLDatabaseProperties
}

// RestorableDeletedSQLDatabaseProperties - The restorable deleted SQL database properties.
type RestorableDeletedSQLDatabaseProperties struct {
	// REQUIRED; ISO 8601 timestamp for the deletion of the database in UTC (e.g., '2024-12-01T00:00:00Z').
	DeletionTimestamp *string

	// REQUIRED; ISO 8601 timestamp for the earliest restore point of the database in UTC (e.g., '2024-12-01T00:00:00Z').
	EarliestRestorePoint *string

	// REQUIRED; ISO 8601 timestamp for the latest restore point of the database in UTC (e.g., '2024-12-02T00:00:00Z').
	LatestRestorePoint *string

	// REQUIRED; The name of the restorable deleted SQL database. This is the name that will be used in the creation payload when
	// restoring from this restorable deleted database.
	RestorableDeletedDatabaseName *string
}

// RestorableDeletedSQLDatabases - A list of restorable deleted SQL databases.
type RestorableDeletedSQLDatabases struct {
	// REQUIRED; Properties of a restorable deleted SQL database.
	Value []RestorableDeletedSQLDatabase

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// RestoreDeletedDatabaseCreationPayload - > [!NOTE] PITR from deleted databases is currently in Preview (learn more [/fabric/fundamentals/preview]).
// Creates a SQL database item by restoring from a restorable deleted database.
type RestoreDeletedDatabaseCreationPayload struct {
	// REQUIRED; The creation mode of the SQL database creation.
	CreationMode *CreationMode

	// REQUIRED; Set the name for the restorable deleted database to be restored.
	RestorableDeletedDatabaseName *string

	// REQUIRED; Set the time to restore the source database in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	RestorePointInTime *time.Time
}

// GetCreationPayload implements the CreationPayloadClassification interface for type RestoreDeletedDatabaseCreationPayload.
func (r *RestoreDeletedDatabaseCreationPayload) GetCreationPayload() *CreationPayload {
	return &CreationPayload{
		CreationMode: r.CreationMode,
	}
}

// RestoreSQLDatabaseCreationPayload - Create a SQL database item creation payload with restoring from a source database
type RestoreSQLDatabaseCreationPayload struct {
	// REQUIRED; The creation mode of the SQL database creation.
	CreationMode *CreationMode

	// Set the time to restore the source database in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	RestorePointInTime *time.Time

	// Set the reference for the source database to be restored from.
	SourceDatabaseReference *ItemReferenceByID
}

// GetCreationPayload implements the CreationPayloadClassification interface for type RestoreSQLDatabaseCreationPayload.
func (r *RestoreSQLDatabaseCreationPayload) GetCreationPayload() *CreationPayload {
	return &CreationPayload{
		CreationMode: r.CreationMode,
	}
}

// SQLDatabase - A SQL database object.
type SQLDatabase struct {
	// REQUIRED; The item type.
	Type *ItemType

	// The item description.
	Description *string

	// The item display name.
	DisplayName *string

	// The SQLDatabase properties.
	Properties *Properties

	// READ-ONLY; The item's default identity.
	DefaultIdentity PrincipalClassification

	// READ-ONLY; The folder ID.
	FolderID *string

	// READ-ONLY; The item ID.
	ID *string

	// READ-ONLY; The item sensitivity label.
	SensitivityLabel *SensitivityLabel

	// READ-ONLY; List of applied tags.
	Tags []ItemTag

	// READ-ONLY; The workspace ID.
	WorkspaceID *string
}

// SQLDatabases - A list of SQL databases.
type SQLDatabases struct {
	// REQUIRED; A list of SQL databases.
	Value []SQLDatabase

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// SensitivityLabel - Represents a sensitivity label applied to an item.
type SensitivityLabel struct {
	// REQUIRED; The sensitivity label ID.
	ID *string
}

// SensitivityLabelSettings - The sensitivity label settings.
type SensitivityLabelSettings struct {
	// REQUIRED; The sensitivity label ID.
	LabelID *string

	// The strategy for applying the sensitivity label.
	SensitivityLabelApplyStrategy *SensitivityLabelApplyStrategy
}

// ServicePrincipal - Represents a Microsoft Entra service principal.
type ServicePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; Service principal specific details. Applicable when the principal type is ServicePrincipal.
	ServicePrincipalDetails *ServicePrincipalDetails
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipal.
func (s *ServicePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalDetails - Service principal specific details. Applicable when the principal type is ServicePrincipal.
type ServicePrincipalDetails struct {
	// READ-ONLY; The service principal's Microsoft Entra AppId.
	AADAppID *string
}

// ServicePrincipalProfilePrincipal - Represents a service principal profile.
type ServicePrincipalProfilePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Service principal profile details. Applicable when the principal type is ServicePrincipalProfile.
	ServicePrincipalProfileDetails *ServicePrincipalProfilePrincipalServicePrincipalProfileDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipalProfilePrincipal.
func (s *ServicePrincipalProfilePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalProfilePrincipalServicePrincipalProfileDetails - Service principal profile details. Applicable when the
// principal type is ServicePrincipalProfile.
type ServicePrincipalProfilePrincipalServicePrincipalProfileDetails struct {
	// The service principal profile's parent principal.
	ParentPrincipal PrincipalClassification
}

// UpdateSQLDatabaseDefinitionRequest - Update SQL database public definition request payload.
type UpdateSQLDatabaseDefinitionRequest struct {
	// REQUIRED; The SQL database public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/sql-database-definition]
	// for more details on the structure of the SQL database
	// definition.
	Definition *Definition
}

// UpdateSQLDatabaseRequest - Update SQL database request.
type UpdateSQLDatabaseRequest struct {
	// The SQL database description. Maximum length is 256 characters.
	Description *string
}

// UserPrincipal - Represents a Microsoft Entra user principal.
type UserPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; User principal specific details. Applicable when the principal type is User.
	UserDetails *UserPrincipalUserDetails
}

// GetPrincipal implements the PrincipalClassification interface for type UserPrincipal.
func (u *UserPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: u.DisplayName,
		ID:          u.ID,
		Type:        u.Type,
	}
}

// UserPrincipalUserDetails - User principal specific details. Applicable when the principal type is User.
type UserPrincipalUserDetails struct {
	// READ-ONLY; The user principal name.
	UserPrincipalName *string
}
