// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package sqldatabase

// CreateSQLDatabaseRequest - Create SQL database request payload.
type CreateSQLDatabaseRequest struct {
	// REQUIRED; The SQL database display name. The display name must follow naming rules according to item type.
	DisplayName *string

	// The SQL database description. Maximum length is 256 characters.
	Description *string

	// The folder ID. If not specified or null, the SQL database is created with the workspace as its folder.
	FolderID *string
}

// ItemTag - Represents a tag applied on an item.
type ItemTag struct {
	// REQUIRED; The name of the tag.
	DisplayName *string

	// REQUIRED; The tag ID.
	ID *string
}

// Properties - The SQL database properties.
type Properties struct {
	// REQUIRED; The connection string of the database.
	ConnectionString *string

	// REQUIRED; The database name.
	DatabaseName *string

	// REQUIRED; The server fully qualified domain name (FQDN).
	ServerFqdn *string
}

// SQLDatabase - A SQL database object.
type SQLDatabase struct {
	// REQUIRED; The item type.
	Type *ItemType

	// The item description.
	Description *string

	// The item display name.
	DisplayName *string

	// The SQLDatabase properties.
	Properties *Properties

	// READ-ONLY; The folder ID.
	FolderID *string

	// READ-ONLY; The item ID.
	ID *string

	// READ-ONLY; List of applied tags.
	Tags []ItemTag

	// READ-ONLY; The workspace ID.
	WorkspaceID *string
}

// SQLDatabases - A list of SQL databases.
type SQLDatabases struct {
	// REQUIRED; A list of SQL databases.
	Value []SQLDatabase

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// UpdateSQLDatabaseRequest - Update SQL database request.
type UpdateSQLDatabaseRequest struct {
	// The SQL database description. Maximum length is 256 characters.
	Description *string
}
