// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package datapipeline

// CreateDataPipelineRequest - Create data pipeline request payload.
type CreateDataPipelineRequest struct {
	// REQUIRED; The data pipeline display name.
	DisplayName *string

	// The data pipeline public definition.
	Definition *Definition

	// The data pipeline description. Maximum length is 256 characters.
	Description *string

	// The folder ID. If not specified or null, the data pipeline is created with the workspace as its folder.
	FolderID *string
}

// DataPipeline - A data pipeline object.
type DataPipeline struct {
	// REQUIRED; The item type.
	Type *ItemType

	// The item description.
	Description *string

	// The item display name.
	DisplayName *string

	// READ-ONLY; The folder ID.
	FolderID *string

	// READ-ONLY; The item ID.
	ID *string

	// READ-ONLY; List of applied tags.
	Tags []ItemTag

	// READ-ONLY; The workspace ID.
	WorkspaceID *string
}

// DataPipelines - A list of data pipelines.
type DataPipelines struct {
	// REQUIRED; A list of data pipelines.
	Value []DataPipeline

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// Definition - Data pipeline public definition object.
type Definition struct {
	// REQUIRED; A list of definition parts.
	Parts []DefinitionPart

	// The format of the item definition.
	Format *string
}

// DefinitionPart - Data pipeline definition part object.
type DefinitionPart struct {
	// The data pipeline part path.
	Path *string

	// The data pipeline part payload.
	Payload *string

	// The payload type.
	PayloadType *PayloadType
}

// DefinitionResponse - Data pipeline public definition response.
type DefinitionResponse struct {
	// READ-ONLY; Data pipeline public definition object.
	Definition *Definition
}

// ItemTag - Represents a tag applied on an item.
type ItemTag struct {
	// REQUIRED; The name of the tag.
	DisplayName *string

	// REQUIRED; The tag ID.
	ID *string
}

// UpdateDataPipelineDefinitionRequest - Update data pipeline public definition request payload.
type UpdateDataPipelineDefinitionRequest struct {
	// REQUIRED; Data pipeline public definition object.
	Definition *Definition
}

// UpdateDataPipelineRequest - Update data pipeline request.
type UpdateDataPipelineRequest struct {
	// The data pipeline description. Maximum length is 256 characters.
	Description *string

	// The data pipeline display name. The display name must follow naming rules according to item type.
	DisplayName *string
}
