// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package paginatedreport

// ItemsClientListPaginatedReportsOptions contains the optional parameters for the ItemsClient.NewListPaginatedReportsPager
// method.
type ItemsClientListPaginatedReportsOptions struct {
	// A token for retrieving the next page of results.
	ContinuationToken *string
}

// ItemsClientUpdatePaginatedReportOptions contains the optional parameters for the ItemsClient.UpdatePaginatedReport method.
type ItemsClientUpdatePaginatedReportOptions struct {
	// placeholder for future optional parameters
}
