// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package anomalydetector

// AnomalyDetector - A AnomalyDetector object.
type AnomalyDetector struct {
	// REQUIRED; The item type.
	Type *ItemType

	// The item description.
	Description *string

	// The item display name.
	DisplayName *string

	// READ-ONLY; The item's default identity.
	DefaultIdentity PrincipalClassification

	// READ-ONLY; The folder ID.
	FolderID *string

	// READ-ONLY; The item ID.
	ID *string

	// READ-ONLY; The item sensitivity label.
	SensitivityLabel *SensitivityLabel

	// READ-ONLY; List of applied tags.
	Tags []ItemTag

	// READ-ONLY; The workspace ID.
	WorkspaceID *string
}

// AnomalyDetectors - A list of Collection Names.
type AnomalyDetectors struct {
	// REQUIRED; A list of Collection Names.
	Value []AnomalyDetector

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// CreateAnomalyDetectorRequest - Create AnomalyDetector request payload.
type CreateAnomalyDetectorRequest struct {
	// REQUIRED; The AnomalyDetector display name. The display name must follow naming rules according to item type.
	DisplayName *string

	// The AnomalyDetector definition.
	Definition *Definition

	// The AnomalyDetector description. Maximum length is 256 characters.
	Description *string

	// The folder ID. If not specified or null, the AnomalyDetector is created with the workspace as its folder.
	FolderID *string

	// The sensitivity label settings for the AnomalyDetector.
	SensitivityLabelSettings *SensitivityLabelSettings
}

// Definition - AnomalyDetector definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/anomalydetector-definition]
// for more details on the structure of the AnomalyDetector
// definition.
type Definition struct {
	// REQUIRED; A list of definition parts.
	Parts []DefinitionPart

	// The format of the item definition. Additional format types may be added over time.
	Format *DefinitionFormat
}

// DefinitionPart - AnomalyDetector definition part object.
type DefinitionPart struct {
	// The AnomalyDetector definition part path.
	Path *string

	// The AnomalyDetector definition part payload.
	Payload *string

	// The payload type.
	PayloadType *PayloadType
}

// DefinitionResponse - AnomalyDetector definition response.
type DefinitionResponse struct {
	// READ-ONLY; AnomalyDetector definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/anomalydetector-definition]
	// for more details on the structure of the AnomalyDetector
	// definition.
	Definition *Definition
}

// EntireTenantPrincipal - Represents a tenant principal
type EntireTenantPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type EntireTenantPrincipal.
func (e *EntireTenantPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: e.DisplayName,
		ID:          e.ID,
		Type:        e.Type,
	}
}

// GroupPrincipal - Represents a security group.
type GroupPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Group specific details. Applicable when the principal type is Group.
	GroupDetails *GroupPrincipalGroupDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type GroupPrincipal.
func (g *GroupPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: g.DisplayName,
		ID:          g.ID,
		Type:        g.Type,
	}
}

// GroupPrincipalGroupDetails - Group specific details. Applicable when the principal type is Group.
type GroupPrincipalGroupDetails struct {
	// The type of the group. Additional group types may be added over time.
	GroupType *GroupType
}

// ItemTag - Represents a tag applied on an item.
type ItemTag struct {
	// REQUIRED; The name of the tag.
	DisplayName *string

	// REQUIRED; The tag ID.
	ID *string
}

// Principal - Represents an identity or a Microsoft Entra group.
type Principal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type Principal.
func (p *Principal) GetPrincipal() *Principal { return p }

// SensitivityLabel - Represents a sensitivity label applied to an item.
type SensitivityLabel struct {
	// REQUIRED; The sensitivity label ID.
	ID *string
}

// SensitivityLabelSettings - The sensitivity label settings.
type SensitivityLabelSettings struct {
	// REQUIRED; The sensitivity label ID.
	LabelID *string

	// The strategy for applying the sensitivity label.
	SensitivityLabelApplyStrategy *SensitivityLabelApplyStrategy
}

// ServicePrincipal - Represents a Microsoft Entra service principal.
type ServicePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; Service principal specific details. Applicable when the principal type is ServicePrincipal.
	ServicePrincipalDetails *ServicePrincipalDetails
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipal.
func (s *ServicePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalDetails - Service principal specific details. Applicable when the principal type is ServicePrincipal.
type ServicePrincipalDetails struct {
	// READ-ONLY; The service principal's Microsoft Entra AppId.
	AADAppID *string
}

// ServicePrincipalProfilePrincipal - Represents a service principal profile.
type ServicePrincipalProfilePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Service principal profile details. Applicable when the principal type is ServicePrincipalProfile.
	ServicePrincipalProfileDetails *ServicePrincipalProfilePrincipalServicePrincipalProfileDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipalProfilePrincipal.
func (s *ServicePrincipalProfilePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalProfilePrincipalServicePrincipalProfileDetails - Service principal profile details. Applicable when the
// principal type is ServicePrincipalProfile.
type ServicePrincipalProfilePrincipalServicePrincipalProfileDetails struct {
	// The service principal profile's parent principal.
	ParentPrincipal PrincipalClassification
}

// UpdateAnomalyDetectorDefinitionRequest - Update AnomalyDetector definition request payload.
type UpdateAnomalyDetectorDefinitionRequest struct {
	// REQUIRED; AnomalyDetector definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/anomalydetector-definition]
	// for more details on the structure of the AnomalyDetector
	// definition.
	Definition *Definition
}

// UpdateAnomalyDetectorRequest - Update AnomalyDetector request.
type UpdateAnomalyDetectorRequest struct {
	// The AnomalyDetector description. Maximum length is 256 characters.
	Description *string

	// The AnomalyDetector display name. The display name must follow naming rules according to item type.
	DisplayName *string
}

// UserPrincipal - Represents a Microsoft Entra user principal.
type UserPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; User principal specific details. Applicable when the principal type is User.
	UserDetails *UserPrincipalUserDetails
}

// GetPrincipal implements the PrincipalClassification interface for type UserPrincipal.
func (u *UserPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: u.DisplayName,
		ID:          u.ID,
		Type:        u.Type,
	}
}

// UserPrincipalUserDetails - User principal specific details. Applicable when the principal type is User.
type UserPrincipalUserDetails struct {
	// READ-ONLY; The user principal name.
	UserPrincipalName *string
}
