# yaml-language-server: $schema=https://taskfile.dev/schema.json
# docs: https://taskfile.dev
#
# Windows:
# winget install Task.Task
#
# Linux:
# sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b ~/.local/bin
# echo 'command -v task >/dev/null || export PATH="$PATH:$HOME/.local/bin"' >> ~/.profile
# source ~/.profile
#
# macOS:
# brew install go-task/tap/go-task
---
version: "3"

vars:
  PWSH: pwsh -NonInteractive -NoProfile -NoLogo -Command

tasks:
  test:
    desc: Run tests
    cmds:
      - go clean -testcache
      - '{{if eq .GITHUB_ACTIONS "true"}}gotestsum --format-hivis --format github-actions --junitfile "testresults.xml" -- ./... -p 4 -timeout 10m -coverprofile="coverage.out" -covermode atomic{{end}}'
      - '{{if ne .GITHUB_ACTIONS "true"}}gotestsum --format-hivis --format pkgname-and-test-fails --junitfile "testresults.xml" -- ./... -p 4 -timeout 10m -coverprofile="coverage.out" -covermode atomic{{end}}'
      - task: test:getcover

  test:getcover:
    desc: Get test coverage results
    internal: true
    cmds:
      - gocov convert coverage.out > coverage.json
      - gocov report coverage.json > coverage.txt
      - cmd: |
          {{ .PWSH }} 'Get-Content coverage.json | gocov-xml > coverage.xml'
        platforms: [windows]
      - cmd: gocov-xml < coverage.json > coverage.xml
        platforms: [linux, darwin]
      - go tool cover -html coverage.out -o coverage.html

  test:tools:
    desc: Install Test Tools
    dir: "{{.goSdkOutput}}"
    cmds:
      - for: [gotestsum, gocov, gocov-xml]
        task: install:{{.ITEM}}

  install:gotestsum:
    desc: Install GoTestSum
    cmds:
      - go install gotest.tools/gotestsum@latest

  install:gocov:
    desc: Install gocov
    cmds:
      - go install github.com/axw/gocov/gocov@latest

  install:gocov-xml:
    desc: Install gocov-xml
    cmds:
      - go install github.com/AlekSi/gocov-xml@latest

  install:gorelease:
    desc: Install gorelease
    cmds:
      - go install golang.org/x/exp/cmd/gorelease@latest

  install:gapidiff:
    desc: Install apidiff
    cmds:
      - go install golang.org/x/exp/cmd/apidiff@latest

  install:modver:
    desc: Install modver
    cmds:
      - go install github.com/bobg/modver/v2/cmd/modver@latest

  # install:go-apidiff:
  #   desc: Install go-apidiff
  #   cmds:
  #     - go install github.com/joelanford/go-apidiff@latest

  api:check:
    desc: Checks what changes have been made to the public API
    vars:
      LATEST:
        sh: git describe --tags --abbrev=0
    cmds:
      - gorelease -base={{.LATEST}}
