// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package mirroredcatalog_test

import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"

	"github.com/microsoft/fabric-sdk-go/fabric/mirroredcatalog"
)

// Generated from example definition
func ExampleItemsClient_NewListMirroredCatalogsPager() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := mirroredcatalog.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	pager := clientFactory.NewItemsClient().NewListMirroredCatalogsPager("cfafbeb1-8037-4d0c-896e-a46fb27ff229", &mirroredcatalog.ItemsClientListMirroredCatalogsOptions{Recursive: nil,
		RootFolderID:      nil,
		ContinuationToken: nil,
	})
	for pager.More() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range page.Value {
			// You could use page here. We use blank identifier for just demo purposes.
			_ = v
		}
		// If the HTTP response code is 200 as defined in example definition, your page structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
		// page.MirroredCatalogs = mirroredcatalog.MirroredCatalogs{
		// 	Value: []mirroredcatalog.MirroredCatalog{
		// 		{
		// 			Type: to.Ptr(mirroredcatalog.ItemTypeMirroredCatalog),
		// 			Description: to.Ptr("Mirror selected ops schemas/tables"),
		// 			DisplayName: to.Ptr("warehouse_ops"),
		// 			ID: to.Ptr("5b218778-e7a5-4d73-8187-f10824047715"),
		// 			WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
		// 			Properties: &mirroredcatalog.Properties{
		// 				ConnectionID: to.Ptr("4eb6b767-e786-45ed-b7cf-d25023e52222"),
		// 				OneLakeTablesPath: to.Ptr("https://onelake.dfs.fabric.microsoft.com/cfafbeb1-8037-4d0c-896e-a46fb27ff229/5b218778-e7a5-4d73-8187-f10824047715/Tables"),
		// 				Scope: []string{
		// 					"Accounting",
		// 					"US"},
		// 					SourceType: to.Ptr("DremioIcebergCatalog"),
		// 					SQLEndpointProperties: &mirroredcatalog.SQLEndpointProperties{
		// 						ConnectionString: to.Ptr("jb7plbunhsduflm44ar4kllxze-r44fqlcgr3nexgcqfsuczoced4.datawarehouse.fabric.microsoft.com"),
		// 						ID: to.Ptr("a2f8c91b-3b7d-4e5a-9f1c-8d4e6b3a2c1f"),
		// 						ProvisioningStatus: to.Ptr(mirroredcatalog.ProvisioningStatusSuccess),
		// 					},
		// 				},
		// 			},
		// 			{
		// 				Type: to.Ptr(mirroredcatalog.ItemTypeMirroredCatalog),
		// 				Description: to.Ptr("Sales data mirroring"),
		// 				DisplayName: to.Ptr("sales_catalog"),
		// 				ID: to.Ptr("a8a1bffa-7eea-49dc-a1d2-6281c1d031f1"),
		// 				WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
		// 				Properties: &mirroredcatalog.Properties{
		// 					ConnectionID: to.Ptr("3cf7f31b-8fe5-5541-ced7-ac8541d66b92"),
		// 					OneLakeTablesPath: to.Ptr("https://onelake.dfs.fabric.microsoft.com/cfafbeb1-8037-4d0c-896e-a46fb27ff229/a8a1bffa-7eea-49dc-a1d2-6281c1d031f1/Tables"),
		// 					Scope: []string{
		// 						"Sales",
		// 						"US"},
		// 						SourceType: to.Ptr("DremioIcebergCatalog"),
		// 						SQLEndpointProperties: &mirroredcatalog.SQLEndpointProperties{
		// 							ConnectionString: to.Ptr("jb7plbunhsduflm44ar4kllxze-r44fqlcgr3nexgcqfsuczoced4.datawarehouse.fabric.microsoft.com"),
		// 							ID: to.Ptr("b3c9d82a-4c8e-5f6b-a02d-9e5f7c4b3d2e"),
		// 							ProvisioningStatus: to.Ptr(mirroredcatalog.ProvisioningStatusSuccess),
		// 						},
		// 					},
		// 			}},
		// 		}
	}
}

// Generated from example definition
func ExampleItemsClient_BeginCreateMirroredCatalog() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := mirroredcatalog.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewItemsClient().BeginCreateMirroredCatalog(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", mirroredcatalog.CreateMirroredCatalogRequest{
		Description: to.Ptr("Mirror selected ops schemas/tables"),
		Definition: &mirroredcatalog.Definition{
			Format: to.Ptr("MirroredCatalogDefinition"),
			Parts: []mirroredcatalog.DefinitionPart{
				{
					Path:        to.Ptr("MirroredCatalogDefinition.json"),
					Payload:     to.Ptr("eyIkc2NoZW1hIjoiaHR0cHM6Ly9kZXZlbG9wZXIubWljcm9zb2Z0LmNvbS9qc29uLXNjaGVtYXMvZmFicmljL2l0ZW0vbWlycm9yZWRDYXRhbG9nL2RlZmluaXRpb24vbWlycm9yZWRDYXRhbG9nRGVmaW5pdGlvbi8xLjAuMC9zY2hlbWEuanNvbiIsInByb3BlcnRpZXMiOnsic291cmNlIjp7InR5cGUiOiJEcmVtaW9JY2ViZXJnQ2F0YWxvZyIsInR5cGVQcm9wZXJ0aWVzIjp7ImNvbm5lY3Rpb25JZCI6IjRlYjZiNzY3LWU3ODYtNDVlZC1iN2NmLWQyNTAyM2U1MjIyMiIsInNjb3BlIjpbIkFjY291bnRpbmciLCJVUyJdfX0sIm1vdW50ZWRUYWJsZXMiOlt7InNvdXJjZSI6eyJ0eXBlUHJvcGVydGllcyI6eyJmdWxseVF1YWxpZmllZFNjb3BlIjpbIkFjY291bnRpbmciLCJVUyIsIlRheGVzIl0sInRhYmxlTmFtZSI6IlRheEluZm8ifX19LHsic291cmNlIjp7InR5cGVQcm9wZXJ0aWVzIjp7ImZ1bGx5UXVhbGlmaWVkU2NvcGUiOlsiQWNjb3VudGluZyIsIlVTIiwiUmVjZWl2YWJsZSJdLCJ0YWJsZU5hbWUiOiJJbnZvaWNlcyJ9fX1dfX0="),
					PayloadType: to.Ptr(mirroredcatalog.PayloadTypeInlineBase64),
				}},
		},
		DisplayName: to.Ptr("warehouse_ops"),
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	_, err = poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
}

// Generated from example definition
func ExampleItemsClient_GetMirroredCatalog() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := mirroredcatalog.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewItemsClient().GetMirroredCatalog(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.MirroredCatalog = mirroredcatalog.MirroredCatalog{
	// 	Type: to.Ptr(mirroredcatalog.ItemTypeMirroredCatalog),
	// 	Description: to.Ptr("Mirror selected ops schemas/tables"),
	// 	DisplayName: to.Ptr("warehouse_ops"),
	// 	ID: to.Ptr("5b218778-e7a5-4d73-8187-f10824047715"),
	// 	WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
	// 	Properties: &mirroredcatalog.Properties{
	// 		ConnectionID: to.Ptr("4eb6b767-e786-45ed-b7cf-d25023e52222"),
	// 		OneLakeTablesPath: to.Ptr("https://onelake.dfs.fabric.microsoft.com/cfafbeb1-8037-4d0c-896e-a46fb27ff229/5b218778-e7a5-4d73-8187-f10824047715/Tables"),
	// 		Scope: []string{
	// 			"Accounting",
	// 			"US"},
	// 			SourceType: to.Ptr("DremioIcebergCatalog"),
	// 			SQLEndpointProperties: &mirroredcatalog.SQLEndpointProperties{
	// 				ConnectionString: to.Ptr("jb7plbunhsduflm44ar4kllxze-r44fqlcgr3nexgcqfsuczoced4.datawarehouse.fabric.microsoft.com"),
	// 				ID: to.Ptr("a2f8c91b-3b7d-4e5a-9f1c-8d4e6b3a2c1f"),
	// 				ProvisioningStatus: to.Ptr(mirroredcatalog.ProvisioningStatusSuccess),
	// 			},
	// 		},
	// 	}
}

// Generated from example definition
func ExampleItemsClient_UpdateMirroredCatalog() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := mirroredcatalog.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewItemsClient().UpdateMirroredCatalog(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", mirroredcatalog.UpdateMirroredCatalogRequest{
		Description: to.Ptr("Updated description for catalog"),
		DisplayName: to.Ptr("warehouse_ops_updated"),
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.MirroredCatalog = mirroredcatalog.MirroredCatalog{
	// 	Type: to.Ptr(mirroredcatalog.ItemTypeMirroredCatalog),
	// 	Description: to.Ptr("Updated description for catalog"),
	// 	DisplayName: to.Ptr("warehouse_ops_updated"),
	// 	ID: to.Ptr("5b218778-e7a5-4d73-8187-f10824047715"),
	// 	WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
	// 	Properties: &mirroredcatalog.Properties{
	// 		ConnectionID: to.Ptr("4eb6b767-e786-45ed-b7cf-d25023e52222"),
	// 		OneLakeTablesPath: to.Ptr("https://onelake.dfs.fabric.microsoft.com/cfafbeb1-8037-4d0c-896e-a46fb27ff229/5b218778-e7a5-4d73-8187-f10824047715/Tables"),
	// 		Scope: []string{
	// 			"Accounting",
	// 			"US"},
	// 			SourceType: to.Ptr("DremioIcebergCatalog"),
	// 			SQLEndpointProperties: &mirroredcatalog.SQLEndpointProperties{
	// 				ConnectionString: to.Ptr("jb7plbunhsduflm44ar4kllxze-r44fqlcgr3nexgcqfsuczoced4.datawarehouse.fabric.microsoft.com"),
	// 				ID: to.Ptr("a2f8c91b-3b7d-4e5a-9f1c-8d4e6b3a2c1f"),
	// 				ProvisioningStatus: to.Ptr(mirroredcatalog.ProvisioningStatusSuccess),
	// 			},
	// 		},
	// 	}
}

// Generated from example definition
func ExampleItemsClient_DeleteMirroredCatalog() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := mirroredcatalog.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	_, err = clientFactory.NewItemsClient().DeleteMirroredCatalog(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
}

// Generated from example definition
func ExampleItemsClient_BeginGetMirroredCatalogDefinition() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := mirroredcatalog.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewItemsClient().BeginGetMirroredCatalogDefinition(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", &mirroredcatalog.ItemsClientBeginGetMirroredCatalogDefinitionOptions{Format: nil})
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	res, err := poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.DefinitionResponse = mirroredcatalog.DefinitionResponse{
	// 	Definition: &mirroredcatalog.Definition{
	// 		Parts: []mirroredcatalog.DefinitionPart{
	// 			{
	// 				Path: to.Ptr("MirroredCatalogDefinition.json"),
	// 				Payload: to.Ptr("eyIkc2NoZW1hIjoiaHR0cHM6Ly9kZXZlbG9wZXIubWljcm9zb2Z0LmNvbS9qc29uLXNjaGVtYXMvZmFicmljL2l0ZW0vbWlycm9yZWRDYXRhbG9nL2RlZmluaXRpb24vbWlycm9yZWRDYXRhbG9nRGVmaW5pdGlvbi8xLjAuMC9zY2hlbWEuanNvbiIsInByb3BlcnRpZXMiOnsic291cmNlIjp7InR5cGUiOiJEcmVtaW9JY2ViZXJnQ2F0YWxvZyIsInR5cGVQcm9wZXJ0aWVzIjp7ImNvbm5lY3Rpb25JZCI6IjRlYjZiNzY3LWU3ODYtNDVlZC1iN2NmLWQyNTAyM2U1MjIyMiIsInNjb3BlIjpbIkFjY291bnRpbmciLCJVUyJdfX0sIm1vdW50ZWRUYWJsZXMiOlt7InNvdXJjZSI6eyJ0eXBlUHJvcGVydGllcyI6eyJmdWxseVF1YWxpZmllZFNjb3BlIjpbIkFjY291bnRpbmciLCJVUyIsIlRheGVzIl0sInRhYmxlTmFtZSI6IlRheEluZm8ifX19LHsic291cmNlIjp7InR5cGVQcm9wZXJ0aWVzIjp7ImZ1bGx5UXVhbGlmaWVkU2NvcGUiOlsiQWNjb3VudGluZyIsIlVTIiwiUmVjZWl2YWJsZSJdLCJ0YWJsZU5hbWUiOiJJbnZvaWNlcyJ9fX1dfX0="),
	// 				PayloadType: to.Ptr(mirroredcatalog.PayloadTypeInlineBase64),
	// 			},
	// 			{
	// 				Path: to.Ptr(".platform"),
	// 				Payload: to.Ptr("eyIkc2NoZW1hIjoiaHR0cHM6Ly9kZXZlbG9wZXIubWljcm9zb2Z0LmNvbS9qc29uLXNjaGVtYXMvZmFicmljL2dpdEludGVncmF0aW9uL3BsYXRmb3JtUHJvcGVydGllcy8yLjAuMC9zY2hlbWEuanNvbiIsIm1ldGFkYXRhIjp7ImRpc3BsYXlOYW1lIjoid2FyZWhvdXNlX29wcyIsImRlc2NyaXB0aW9uIjoiTWlycm9yIHNlbGVjdGVkIG9wcyBzY2hlbWFzL3RhYmxlcyJ9LCJjb25maWciOnsidmVyc2lvbiI6IjIuMCIsImxvZ2ljYWxJZCI6IjViMjE4Nzc4LWU3YTUtNGQ3My04MTg3LWYxMDgyNDA0NzcxNSJ9fQ=="),
	// 				PayloadType: to.Ptr(mirroredcatalog.PayloadTypeInlineBase64),
	// 		}},
	// 	},
	// }
}

// Generated from example definition
func ExampleItemsClient_BeginUpdateMirroredCatalogDefinition() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := mirroredcatalog.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewItemsClient().BeginUpdateMirroredCatalogDefinition(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", mirroredcatalog.UpdateMirroredCatalogDefinitionRequest{
		Definition: &mirroredcatalog.Definition{
			Parts: []mirroredcatalog.DefinitionPart{
				{
					Path:        to.Ptr("MirroredCatalogDefinition.json"),
					Payload:     to.Ptr("eyIkc2NoZW1hIjoiaHR0cHM6Ly9kZXZlbG9wZXIubWljcm9zb2Z0LmNvbS9qc29uLXNjaGVtYXMvZmFicmljL2l0ZW0vbWlycm9yZWRDYXRhbG9nL2RlZmluaXRpb24vbWlycm9yZWRDYXRhbG9nRGVmaW5pdGlvbi8xLjAuMC9zY2hlbWEuanNvbiIsInByb3BlcnRpZXMiOnsic291cmNlIjp7InR5cGUiOiJEcmVtaW9JY2ViZXJnQ2F0YWxvZyIsInR5cGVQcm9wZXJ0aWVzIjp7ImNvbm5lY3Rpb25JZCI6IjRlYjZiNzY3LWU3ODYtNDVlZC1iN2NmLWQyNTAyM2U1MjIyMiIsInNjb3BlIjpbIkFjY291bnRpbmciLCJVUyJdfX0sIm1vdW50ZWRUYWJsZXMiOlt7InNvdXJjZSI6eyJ0eXBlUHJvcGVydGllcyI6eyJmdWxseVF1YWxpZmllZFNjb3BlIjpbIkFjY291bnRpbmciLCJVUyIsIlRheGVzIl0sInRhYmxlTmFtZSI6IlRheEluZm8ifX19LHsic291cmNlIjp7InR5cGVQcm9wZXJ0aWVzIjp7ImZ1bGx5UXVhbGlmaWVkU2NvcGUiOlsiQWNjb3VudGluZyIsIlVTIiwiVGF4ZXMiXSwidGFibGVOYW1lIjoiTmV3VGFibGUifX19LHsic291cmNlIjp7InR5cGVQcm9wZXJ0aWVzIjp7ImZ1bGx5UXVhbGlmaWVkU2NvcGUiOlsiQWNjb3VudGluZyIsIlVTIiwiUmVjZWl2YWJsZSJdLCJ0YWJsZU5hbWUiOiJJbnZvaWNlcyJ9fX0seyJzb3VyY2UiOnsidHlwZVByb3BlcnRpZXMiOnsiZnVsbHlRdWFsaWZpZWRTY29wZSI6WyJBY2NvdW50aW5nIiwiVVMiLCJSZWNlaXZhYmxlIl0sInRhYmxlTmFtZSI6IlBheWFibGVzIn19fV19fQ=="),
					PayloadType: to.Ptr(mirroredcatalog.PayloadTypeInlineBase64),
				}},
		},
	}, &mirroredcatalog.ItemsClientBeginUpdateMirroredCatalogDefinitionOptions{UpdateMetadata: nil})
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	_, err = poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
}
