// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package sqlendpoint

import "time"

// ConnectionStringResponse - The SQL connection string for the workspace containing this SQL endpoint.
type ConnectionStringResponse struct {
	// The SQL connection string for the workspace containing this SQL endpoint.
	ConnectionString *string
}

// Duration - A duration.
type Duration struct {
	// REQUIRED; The unit of time for the duration. Additional duration types may be added over time.
	TimeUnit *TimeUnit

	// REQUIRED; The number of timeUnits in the duration.
	Value *float32
}

// EntireTenantPrincipal - Represents a tenant principal
type EntireTenantPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type EntireTenantPrincipal.
func (e *EntireTenantPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: e.DisplayName,
		ID:          e.ID,
		Type:        e.Type,
	}
}

// ErrorRelatedResource - The error related resource details object.
type ErrorRelatedResource struct {
	// READ-ONLY; The resource ID that's involved in the error.
	ResourceID *string

	// READ-ONLY; The type of the resource that's involved in the error.
	ResourceType *string
}

// ErrorResponseDetails - The error response details.
type ErrorResponseDetails struct {
	// READ-ONLY; A specific identifier that provides information about an error condition, allowing for standardized communication
	// between our service and its users.
	ErrorCode *string

	// READ-ONLY; A human readable representation of the error.
	Message *string

	// READ-ONLY; The error related resource details.
	RelatedResource *ErrorRelatedResource
}

// GroupPrincipal - Represents a security group.
type GroupPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Group specific details. Applicable when the principal type is Group.
	GroupDetails *GroupPrincipalGroupDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type GroupPrincipal.
func (g *GroupPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: g.DisplayName,
		ID:          g.ID,
		Type:        g.Type,
	}
}

// GroupPrincipalGroupDetails - Group specific details. Applicable when the principal type is Group.
type GroupPrincipalGroupDetails struct {
	// The type of the group. Additional group types may be added over time.
	GroupType *GroupType
}

// ItemTag - Represents a tag applied on an item.
type ItemTag struct {
	// REQUIRED; The name of the tag.
	DisplayName *string

	// REQUIRED; The tag ID.
	ID *string
}

// Principal - Represents an identity or a Microsoft Entra group.
type Principal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type Principal.
func (p *Principal) GetPrincipal() *Principal { return p }

// RefreshMetadataRequest - Refresh SQL analaytics endpoint request payload.
type RefreshMetadataRequest struct {
	// When set to true, this property instructs the system to drop and recreate all tables on SQL analytics endpoint during the
	// refresh process. Use this option if you need to fully rebuild tables from
	// their source definitions, for example to resolve inconsistencies or ensure a clean refresh. The default value is false.
	RecreateTables *bool

	// The request duration before timing out. The default value is 15 minutes.
	Timeout *Duration
}

// SQLAuditSettings - The current state of audit settings for an item.
type SQLAuditSettings struct {
	// REQUIRED; Audit actions and groups.
	AuditActionsAndGroups []string

	// REQUIRED; Retention days. 0 indicates indefinite retention period.
	RetentionDays *int32

	// REQUIRED; Audit settings state type.
	State *AuditSettingsState
}

// SQLAuditSettingsUpdate - Audit settings update request.
type SQLAuditSettingsUpdate struct {
	// Retention days.
	RetentionDays *int32

	// Audit settings state type.
	State *AuditSettingsState
}

// SQLEndpoint - A SQL endpoint object.
type SQLEndpoint struct {
	// REQUIRED; The item type.
	Type *ItemType

	// The item description.
	Description *string

	// The item display name.
	DisplayName *string

	// READ-ONLY; The item's default identity.
	DefaultIdentity PrincipalClassification

	// READ-ONLY; The folder ID.
	FolderID *string

	// READ-ONLY; The item ID.
	ID *string

	// READ-ONLY; The item sensitivity label.
	SensitivityLabel *SensitivityLabel

	// READ-ONLY; List of applied tags.
	Tags []ItemTag

	// READ-ONLY; The workspace ID.
	WorkspaceID *string
}

// SQLEndpoints - A list of SQL endpoints.
type SQLEndpoints struct {
	// REQUIRED; A list of SQL endpoints.
	Value []SQLEndpoint

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// SensitivityLabel - Represents a sensitivity label applied to an item.
type SensitivityLabel struct {
	// REQUIRED; The sensitivity label ID.
	ID *string
}

// ServicePrincipal - Represents a Microsoft Entra service principal.
type ServicePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; Service principal specific details. Applicable when the principal type is ServicePrincipal.
	ServicePrincipalDetails *ServicePrincipalDetails
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipal.
func (s *ServicePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalDetails - Service principal specific details. Applicable when the principal type is ServicePrincipal.
type ServicePrincipalDetails struct {
	// READ-ONLY; The service principal's Microsoft Entra AppId.
	AADAppID *string
}

// ServicePrincipalProfilePrincipal - Represents a service principal profile.
type ServicePrincipalProfilePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Service principal profile details. Applicable when the principal type is ServicePrincipalProfile.
	ServicePrincipalProfileDetails *ServicePrincipalProfilePrincipalServicePrincipalProfileDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipalProfilePrincipal.
func (s *ServicePrincipalProfilePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalProfilePrincipalServicePrincipalProfileDetails - Service principal profile details. Applicable when the
// principal type is ServicePrincipalProfile.
type ServicePrincipalProfilePrincipalServicePrincipalProfileDetails struct {
	// The service principal profile's parent principal.
	ParentPrincipal PrincipalClassification
}

// TableSyncStatus - A table synchronization status object.
type TableSyncStatus struct {
	// REQUIRED; The date and time when the table synchronization completed in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	EndDateTime *time.Time

	// REQUIRED; The date and time when the table synchronization was successful in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	LastSuccessfulSyncDateTime *time.Time

	// REQUIRED; The date and time when the table synchronization started in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	StartDateTime *time.Time

	// REQUIRED; Whether the table synchronized without errors.
	Status *SyncStatus

	// REQUIRED; The name of the table that synchronized.
	TableName *string

	// The error response details
	Error *ErrorResponseDetails
}

// TableSyncStatuses - A list of table synchronization statuses.
type TableSyncStatuses struct {
	// REQUIRED; A list of table synchronization statuses.
	Value []TableSyncStatus
}

// UserPrincipal - Represents a Microsoft Entra user principal.
type UserPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; User principal specific details. Applicable when the principal type is User.
	UserDetails *UserPrincipalUserDetails
}

// GetPrincipal implements the PrincipalClassification interface for type UserPrincipal.
func (u *UserPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: u.DisplayName,
		ID:          u.ID,
		Type:        u.Type,
	}
}

// UserPrincipalUserDetails - User principal specific details. Applicable when the principal type is User.
type UserPrincipalUserDetails struct {
	// READ-ONLY; The user principal name.
	UserPrincipalName *string
}
