// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package core

// ConnectionClassification provides polymorphic access to related types.
// Call the interface's GetConnection() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *Connection, *OnPremisesGatewayConnection, *OnPremisesGatewayPersonalConnection, *PersonalCloudConnection, *ShareableCloudConnection,
// - *VirtualNetworkGatewayConnection
type ConnectionClassification interface {
	// GetConnection returns the Connection content of the underlying type.
	GetConnection() *Connection
}

// ConnectionDetailsParameterClassification provides polymorphic access to related types.
// Call the interface's GetConnectionDetailsParameter() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ConnectionDetailsBooleanParameter, *ConnectionDetailsDateParameter, *ConnectionDetailsDateTimeParameter, *ConnectionDetailsDateTimeZoneParameter,
// - *ConnectionDetailsDurationParameter, *ConnectionDetailsNumberParameter, *ConnectionDetailsParameter, *ConnectionDetailsTextParameter,
// - *ConnectionDetailsTimeParameter
type ConnectionDetailsParameterClassification interface {
	// GetConnectionDetailsParameter returns the ConnectionDetailsParameter content of the underlying type.
	GetConnectionDetailsParameter() *ConnectionDetailsParameter
}

// CreateConnectionRequestClassification provides polymorphic access to related types.
// Call the interface's GetCreateConnectionRequest() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *CreateCloudConnectionRequest, *CreateConnectionRequest, *CreateOnPremisesConnectionRequest, *CreateVirtualNetworkGatewayConnectionRequest
type CreateConnectionRequestClassification interface {
	// GetCreateConnectionRequest returns the CreateConnectionRequest content of the underlying type.
	GetCreateConnectionRequest() *CreateConnectionRequest
}

// CreateGatewayRequestClassification provides polymorphic access to related types.
// Call the interface's GetCreateGatewayRequest() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *CreateGatewayRequest, *CreateVirtualNetworkGatewayRequest
type CreateGatewayRequestClassification interface {
	// GetCreateGatewayRequest returns the CreateGatewayRequest content of the underlying type.
	GetCreateGatewayRequest() *CreateGatewayRequest
}

// CredentialsClassification provides polymorphic access to related types.
// Call the interface's GetCredentials() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AnonymousCredentials, *BasicCredentials, *Credentials, *KeyCredentials, *KeyPairCredentials, *ServicePrincipalCredentials,
// - *SharedAccessSignatureCredentials, *WindowsCredentials, *WindowsWithoutImpersonationCredentials, *WorkspaceIdentityCredentials
type CredentialsClassification interface {
	// GetCredentials returns the Credentials content of the underlying type.
	GetCredentials() *Credentials
}

// ExternalDataShareAcceptRequestPayloadClassification provides polymorphic access to related types.
// Call the interface's GetExternalDataShareAcceptRequestPayload() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ExternalDataShareAcceptRequestPayload, *ShortcutCreationPayload
type ExternalDataShareAcceptRequestPayloadClassification interface {
	// GetExternalDataShareAcceptRequestPayload returns the ExternalDataShareAcceptRequestPayload content of the underlying type.
	GetExternalDataShareAcceptRequestPayload() *ExternalDataShareAcceptRequestPayload
}

// GatewayClassification provides polymorphic access to related types.
// Call the interface's GetGateway() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *Gateway, *OnPremisesGateway, *OnPremisesGatewayPersonal, *VirtualNetworkGateway
type GatewayClassification interface {
	// GetGateway returns the Gateway content of the underlying type.
	GetGateway() *Gateway
}

// GitCredentialsClassification provides polymorphic access to related types.
// Call the interface's GetGitCredentials() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AutomaticGitCredentials, *ConfiguredConnectionGitCredentials, *GitCredentials
type GitCredentialsClassification interface {
	// GetGitCredentials returns the GitCredentials content of the underlying type.
	GetGitCredentials() *GitCredentials
}

// GitCredentialsConfigurationResponseClassification provides polymorphic access to related types.
// Call the interface's GetGitCredentialsConfigurationResponse() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AutomaticGitCredentialsResponse, *ConfiguredConnectionGitCredentialsResponse, *GitCredentialsConfigurationResponse,
// - *NoneGitCredentialsResponse
type GitCredentialsConfigurationResponseClassification interface {
	// GetGitCredentialsConfigurationResponse returns the GitCredentialsConfigurationResponse content of the underlying type.
	GetGitCredentialsConfigurationResponse() *GitCredentialsConfigurationResponse
}

// GitProviderDetailsClassification provides polymorphic access to related types.
// Call the interface's GetGitProviderDetails() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *AzureDevOpsDetails, *GitHubDetails, *GitProviderDetails
type GitProviderDetailsClassification interface {
	// GetGitProviderDetails returns the GitProviderDetails content of the underlying type.
	GetGitProviderDetails() *GitProviderDetails
}

// ItemReferenceClassification provides polymorphic access to related types.
// Call the interface's GetItemReference() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *ItemReference, *ItemReferenceByID
type ItemReferenceClassification interface {
	// GetItemReference returns the ItemReference content of the underlying type.
	GetItemReference() *ItemReference
}

// MonthlyOccurrenceClassification provides polymorphic access to related types.
// Call the interface's GetMonthlyOccurrence() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *DayOfMonth, *MonthlyOccurrence, *OrdinalWeekday
type MonthlyOccurrenceClassification interface {
	// GetMonthlyOccurrence returns the MonthlyOccurrence content of the underlying type.
	GetMonthlyOccurrence() *MonthlyOccurrence
}

// OneLakeDiagnosticSettingsDestinationInfoClassification provides polymorphic access to related types.
// Call the interface's GetOneLakeDiagnosticSettingsDestinationInfo() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *LakehouseOneLakeDiagnosticSettingsDestination, *OneLakeDiagnosticSettingsDestinationInfo
type OneLakeDiagnosticSettingsDestinationInfoClassification interface {
	// GetOneLakeDiagnosticSettingsDestinationInfo returns the OneLakeDiagnosticSettingsDestinationInfo content of the underlying type.
	GetOneLakeDiagnosticSettingsDestinationInfo() *OneLakeDiagnosticSettingsDestinationInfo
}

// ScheduleConfigClassification provides polymorphic access to related types.
// Call the interface's GetScheduleConfig() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *CronScheduleConfig, *DailyScheduleConfig, *MonthlyScheduleConfig, *ScheduleConfig, *WeeklyScheduleConfig
type ScheduleConfigClassification interface {
	// GetScheduleConfig returns the ScheduleConfig content of the underlying type.
	GetScheduleConfig() *ScheduleConfig
}

// TagScopeClassification provides polymorphic access to related types.
// Call the interface's GetTagScope() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *DomainTagScope, *TagScope, *TenantTagScope
type TagScopeClassification interface {
	// GetTagScope returns the TagScope content of the underlying type.
	GetTagScope() *TagScope
}

// TransformClassification provides polymorphic access to related types.
// Call the interface's GetTransform() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *CSVToDeltaTransform, *Transform
type TransformClassification interface {
	// GetTransform returns the Transform content of the underlying type.
	GetTransform() *Transform
}

// UpdateConnectionRequestClassification provides polymorphic access to related types.
// Call the interface's GetUpdateConnectionRequest() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *UpdateConnectionRequest, *UpdateOnPremisesGatewayConnectionRequest, *UpdateOnPremisesGatewayPersonalConnectionRequest,
// - *UpdatePersonalCloudConnectionRequest, *UpdateShareableCloudConnectionRequest, *UpdateVirtualNetworkGatewayConnectionRequest
type UpdateConnectionRequestClassification interface {
	// GetUpdateConnectionRequest returns the UpdateConnectionRequest content of the underlying type.
	GetUpdateConnectionRequest() *UpdateConnectionRequest
}

// UpdateGatewayRequestClassification provides polymorphic access to related types.
// Call the interface's GetUpdateGatewayRequest() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *UpdateGatewayRequest, *UpdateOnPremisesGatewayRequest, *UpdateVirtualNetworkGatewayRequest
type UpdateGatewayRequestClassification interface {
	// GetUpdateGatewayRequest returns the UpdateGatewayRequest content of the underlying type.
	GetUpdateGatewayRequest() *UpdateGatewayRequest
}

// UpdateGitCredentialsRequestClassification provides polymorphic access to related types.
// Call the interface's GetUpdateGitCredentialsRequest() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *UpdateGitCredentialsRequest, *UpdateGitCredentialsToAutomaticRequest, *UpdateGitCredentialsToConfiguredConnectionRequest,
// - *UpdateGitCredentialsToNoneRequest
type UpdateGitCredentialsRequestClassification interface {
	// GetUpdateGitCredentialsRequest returns the UpdateGitCredentialsRequest content of the underlying type.
	GetUpdateGitCredentialsRequest() *UpdateGitCredentialsRequest
}
