// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package graphmodel_test

import (
	"context"
	"log"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"
	"github.com/Azure/azure-sdk-for-go/sdk/azidentity"

	"github.com/microsoft/fabric-sdk-go/fabric/graphmodel"
)

// Generated from example definition
func ExampleItemsClient_NewListGraphModelsPager() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	pager := clientFactory.NewItemsClient().NewListGraphModelsPager("cfafbeb1-8037-4d0c-896e-a46fb27ff229", &graphmodel.ItemsClientListGraphModelsOptions{ContinuationToken: nil})
	for pager.More() {
		page, err := pager.NextPage(ctx)
		if err != nil {
			log.Fatalf("failed to advance page: %v", err)
		}
		for _, v := range page.Value {
			// You could use page here. We use blank identifier for just demo purposes.
			_ = v
		}
		// If the HTTP response code is 200 as defined in example definition, your page structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
		// page.GraphModels = graphmodel.GraphModels{
		// 	Value: []graphmodel.GraphModel{
		// 		{
		// 			Type: to.Ptr(graphmodel.ItemTypeGraphModel),
		// 			Description: to.Ptr("A GraphModel description."),
		// 			DisplayName: to.Ptr("GraphModel Name 1"),
		// 			ID: to.Ptr("3546052c-ae64-4526-b1a8-52af7761426f"),
		// 			WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
		// 		},
		// 		{
		// 			Type: to.Ptr(graphmodel.ItemTypeGraphModel),
		// 			Description: to.Ptr("A GraphModel description."),
		// 			DisplayName: to.Ptr("GraphModel Name 2"),
		// 			ID: to.Ptr("f697fb63-abd4-4399-9548-be7e3c3c0dac"),
		// 			WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
		// 	}},
		// }
	}
}

// Generated from example definition
func ExampleItemsClient_BeginCreateGraphModel_createAGraphModelExample() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewItemsClient().BeginCreateGraphModel(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", graphmodel.CreateGraphModelRequest{
		Description: to.Ptr("A GraphModel description."),
		DisplayName: to.Ptr("GraphModel 1"),
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	_, err = poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
}

// Generated from example definition
func ExampleItemsClient_BeginCreateGraphModel_createAGraphModelWithPublicDefinitionExample() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewItemsClient().BeginCreateGraphModel(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", graphmodel.CreateGraphModelRequest{
		Description: to.Ptr("A GraphModel description."),
		Definition: &graphmodel.PublicDefinition{
			Format: to.Ptr(graphmodel.DefinitionFormatJSON),
			Parts: []graphmodel.PublicDefinitionPart{
				{
					Path:        to.Ptr("graphType.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr("graphDefinition.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr("dataSources.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr("stylingConfiguration.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr(".platform"),
					Payload:     to.Ptr("ZG90UGxhdGZvcm1CYXNlNjRTdHJpbmc="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				}},
		},
		DisplayName: to.Ptr("GraphModel 1"),
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	_, err = poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
}

// Generated from example definition
func ExampleItemsClient_GetGraphModel() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewItemsClient().GetGraphModel(ctx, "f089354e-8366-4e18-aea3-4cb4a3a50b48", "41ce06d1-d81b-4ea0-bc6d-2ce3dd2f8e87", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.GraphModel = graphmodel.GraphModel{
	// 	Type: to.Ptr(graphmodel.ItemTypeGraphModel),
	// 	Description: to.Ptr("A GraphModel description."),
	// 	DisplayName: to.Ptr("GraphModel 1"),
	// 	ID: to.Ptr("5b218778-e7a5-4d73-8187-f10824047715"),
	// 	WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
	// }
}

// Generated from example definition
func ExampleItemsClient_UpdateGraphModel() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewItemsClient().UpdateGraphModel(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", graphmodel.UpdateGraphModelRequest{
		Description: to.Ptr("GraphModel's New description"),
		DisplayName: to.Ptr("GraphModel's New name"),
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.GraphModel = graphmodel.GraphModel{
	// 	Type: to.Ptr(graphmodel.ItemTypeGraphModel),
	// 	Description: to.Ptr("GraphModel's New description"),
	// 	DisplayName: to.Ptr("GraphModel's New name"),
	// 	ID: to.Ptr("5b218778-e7a5-4d73-8187-f10824047715"),
	// 	WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
	// }
}

// Generated from example definition
func ExampleItemsClient_DeleteGraphModel() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	_, err = clientFactory.NewItemsClient().DeleteGraphModel(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
}

// Generated from example definition
func ExampleItemsClient_BeginGetGraphModelDefinition() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewItemsClient().BeginGetGraphModelDefinition(ctx, "6e335e92-a2a2-4b5a-970a-bd6a89fbb765", "cfafbeb1-8037-4d0c-896e-a46fb27ff229", &graphmodel.ItemsClientBeginGetGraphModelDefinitionOptions{Format: nil})
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	res, err := poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.DefinitionResponse = graphmodel.DefinitionResponse{
	// 	Definition: &graphmodel.PublicDefinition{
	// 		Format: to.Ptr(graphmodel.DefinitionFormatJSON),
	// 		Parts: []graphmodel.PublicDefinitionPart{
	// 			{
	// 				Path: to.Ptr("graphType.json"),
	// 				Payload: to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
	// 				PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
	// 			},
	// 			{
	// 				Path: to.Ptr("graphDefinition.json"),
	// 				Payload: to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
	// 				PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
	// 			},
	// 			{
	// 				Path: to.Ptr("dataSources.json"),
	// 				Payload: to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
	// 				PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
	// 			},
	// 			{
	// 				Path: to.Ptr("stylingConfiguration.json"),
	// 				Payload: to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
	// 				PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
	// 			},
	// 			{
	// 				Path: to.Ptr(".platform"),
	// 				Payload: to.Ptr("ZG90UGxhdGZvcm1CYXNlNjRTdHJpbmc="),
	// 				PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
	// 		}},
	// 	},
	// }
}

// Generated from example definition
func ExampleItemsClient_BeginUpdateGraphModelDefinition() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	poller, err := clientFactory.NewItemsClient().BeginUpdateGraphModelDefinition(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", graphmodel.UpdateGraphModelDefinitionRequest{
		Definition: &graphmodel.PublicDefinition{
			Format: to.Ptr(graphmodel.DefinitionFormatJSON),
			Parts: []graphmodel.PublicDefinitionPart{
				{
					Path:        to.Ptr("graphType.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr("graphDefinition.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr("dataSources.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr("stylingConfiguration.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				},
				{
					Path:        to.Ptr(".platform"),
					Payload:     to.Ptr("ZG90UGxhdGZvcm1CYXNlNjRTdHJpbmc="),
					PayloadType: to.Ptr(graphmodel.PayloadTypeInlineBase64),
				}},
		},
	}, &graphmodel.ItemsClientBeginUpdateGraphModelDefinitionOptions{UpdateMetadata: to.Ptr(true)})
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	_, err = poller.PollUntilDone(ctx, nil)
	if err != nil {
		log.Fatalf("failed to pull the result: %v", err)
	}
}

// Generated from example definition
func ExampleItemsClient_ExecuteQueryPreview() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	_, err = clientFactory.NewItemsClient().ExecuteQueryPreview(ctx, "cfafbeb1-8037-4d0c-896e-a46fb27ff229", "5b218778-e7a5-4d73-8187-f10824047715", true, graphmodel.ExecuteQueryRequest{
		Query: to.Ptr("MATCH (node_station:`station`) RETURN TO_JSON_STRING(node_station) AS `station` LIMIT 10;"),
	}, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
}

// Generated from example definition
func ExampleItemsClient_GetQueryableGraphTypePreview() {
	cred, err := azidentity.NewDefaultAzureCredential(nil)
	if err != nil {
		log.Fatalf("failed to obtain a credential: %v", err)
	}
	ctx := context.Background()
	clientFactory, err := graphmodel.NewClientFactory(cred, nil, nil)
	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}
	res, err := clientFactory.NewItemsClient().GetQueryableGraphTypePreview(ctx, "f089354e-8366-4e18-aea3-4cb4a3a50b48", "41ce06d1-d81b-4ea0-bc6d-2ce3dd2f8e87", true, nil)
	if err != nil {
		log.Fatalf("failed to finish the request: %v", err)
	}
	// You could use response here. We use blank identifier for just demo purposes.
	_ = res
	// If the HTTP response code is 200 as defined in example definition, your response structure would look as follows. Please pay attention that all the values in the output are fake values for just demo purposes.
	// res.GraphType = graphmodel.GraphType{
	// 	EdgeTypes: []graphmodel.EdgeType{
	// 		{
	// 			Alias: to.Ptr("3ef6a474-ef38-4923-abcf-6f2e9230f1eb"),
	// 			DestinationNodeType: &graphmodel.NodeTypeReference{
	// 				Alias: to.Ptr("dced4642-b93d-4da4-815c-a171932043a4"),
	// 			},
	// 			Labels: []string{
	// 				"customerProducts"},
	// 				Properties: []graphmodel.Property{
	// 				},
	// 				SourceNodeType: &graphmodel.NodeTypeReference{
	// 					Alias: to.Ptr("096a5133-fd82-4000-ac8a-404532ab6fd6"),
	// 				},
	// 		}},
	// 		NodeTypes: []graphmodel.NodeType{
	// 			{
	// 				Alias: to.Ptr("096a5133-fd82-4000-ac8a-404532ab6fd6"),
	// 				Labels: []string{
	// 					"customer"},
	// 					PrimaryKeyProperties: []string{
	// 						"customerIDK"},
	// 						Properties: []graphmodel.Property{
	// 							{
	// 								Name: to.Ptr("customerIDK"),
	// 								Type: to.Ptr("INT"),
	// 							},
	// 							{
	// 								Name: to.Ptr("firstName"),
	// 								Type: to.Ptr("STRING"),
	// 							},
	// 							{
	// 								Name: to.Ptr("lastName"),
	// 								Type: to.Ptr("STRING"),
	// 							},
	// 							{
	// 								Name: to.Ptr("fullName"),
	// 								Type: to.Ptr("STRING"),
	// 						}},
	// 					},
	// 					{
	// 						Alias: to.Ptr("dced4642-b93d-4da4-815c-a171932043a4"),
	// 						Labels: []string{
	// 							"products"},
	// 							PrimaryKeyProperties: []string{
	// 								"productIDK"},
	// 								Properties: []graphmodel.Property{
	// 									{
	// 										Name: to.Ptr("productIDK"),
	// 										Type: to.Ptr("INT"),
	// 									},
	// 									{
	// 										Name: to.Ptr("productNumber"),
	// 										Type: to.Ptr("STRING"),
	// 									},
	// 									{
	// 										Name: to.Ptr("productName"),
	// 										Type: to.Ptr("STRING"),
	// 									},
	// 									{
	// 										Name: to.Ptr("modelName"),
	// 										Type: to.Ptr("STRING"),
	// 									},
	// 									{
	// 										Name: to.Ptr("makeFlag"),
	// 										Type: to.Ptr("INT"),
	// 									},
	// 									{
	// 										Name: to.Ptr("standardCost"),
	// 										Type: to.Ptr("FLOAT"),
	// 									},
	// 									{
	// 										Name: to.Ptr("listPrice"),
	// 										Type: to.Ptr("FLOAT"),
	// 									},
	// 									{
	// 										Name: to.Ptr("subCategoryIDFK"),
	// 										Type: to.Ptr("INT"),
	// 								}},
	// 						}},
	// 					}
}
