// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package eventstream

// ItemsClientCreateEventstreamResponse contains the response from method ItemsClient.BeginCreateEventstream.
type ItemsClientCreateEventstreamResponse struct {
	// An eventstream object.
	Eventstream
}

// ItemsClientDeleteEventstreamResponse contains the response from method ItemsClient.DeleteEventstream.
type ItemsClientDeleteEventstreamResponse struct {
	// placeholder for future response values
}

// ItemsClientGetEventstreamResponse contains the response from method ItemsClient.GetEventstream.
type ItemsClientGetEventstreamResponse struct {
	// An eventstream object.
	Eventstream
}

// ItemsClientListEventstreamsResponse contains the response from method ItemsClient.NewListEventstreamsPager.
type ItemsClientListEventstreamsResponse struct {
	// A list of eventstreams.
	Eventstreams
}

// ItemsClientUpdateEventstreamResponse contains the response from method ItemsClient.UpdateEventstream.
type ItemsClientUpdateEventstreamResponse struct {
	// An eventstream object.
	Eventstream
}
