// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package fake

import (
	"context"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"regexp"
	"strconv"
	"strings"

	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/fake/server"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"

	"github.com/microsoft/fabric-sdk-go/fabric/spark"
)

// CapacitySettingsServer is a fake server for instances of the spark.CapacitySettingsClient type.
type CapacitySettingsServer struct {
	// GetSparkSettingsBeta is the fake for method CapacitySettingsClient.GetSparkSettingsBeta
	// HTTP status codes to indicate success: http.StatusOK
	GetSparkSettingsBeta func(ctx context.Context, capacityID string, beta bool, options *spark.CapacitySettingsClientGetSparkSettingsBetaOptions) (resp azfake.Responder[spark.CapacitySettingsClientGetSparkSettingsBetaResponse], errResp azfake.ErrorResponder)

	// UpdateSparkSettingsBeta is the fake for method CapacitySettingsClient.UpdateSparkSettingsBeta
	// HTTP status codes to indicate success: http.StatusOK
	UpdateSparkSettingsBeta func(ctx context.Context, capacityID string, beta bool, updateCapacitySettingsRequest spark.UpdateCapacitySparkSettingsRequest, options *spark.CapacitySettingsClientUpdateSparkSettingsBetaOptions) (resp azfake.Responder[spark.CapacitySettingsClientUpdateSparkSettingsBetaResponse], errResp azfake.ErrorResponder)
}

// NewCapacitySettingsServerTransport creates a new instance of CapacitySettingsServerTransport with the provided implementation.
// The returned CapacitySettingsServerTransport instance is connected to an instance of spark.CapacitySettingsClient via the
// azcore.ClientOptions.Transporter field in the client's constructor parameters.
func NewCapacitySettingsServerTransport(srv *CapacitySettingsServer) *CapacitySettingsServerTransport {
	return &CapacitySettingsServerTransport{srv: srv}
}

// CapacitySettingsServerTransport connects instances of spark.CapacitySettingsClient to instances of CapacitySettingsServer.
// Don't use this type directly, use NewCapacitySettingsServerTransport instead.
type CapacitySettingsServerTransport struct {
	srv *CapacitySettingsServer
}

// Do implements the policy.Transporter interface for CapacitySettingsServerTransport.
func (c *CapacitySettingsServerTransport) Do(req *http.Request) (*http.Response, error) {
	rawMethod := req.Context().Value(runtime.CtxAPINameKey{})
	method, ok := rawMethod.(string)
	if !ok {
		return nil, nonRetriableError{errors.New("unable to dispatch request, missing value for CtxAPINameKey")}
	}

	parts := strings.Split(method, ".")
	method = parts[1] + "." + parts[2]
	return c.dispatchToMethodFake(req, method)
}

func (c *CapacitySettingsServerTransport) dispatchToMethodFake(req *http.Request, method string) (*http.Response, error) {
	resultChan := make(chan result)
	defer close(resultChan)

	go func() {
		var intercepted bool
		var res result
		if capacitySettingsServerTransportInterceptor != nil {
			res.resp, res.err, intercepted = capacitySettingsServerTransportInterceptor.Do(req)
		}
		if !intercepted {
			switch method {
			case "CapacitySettingsClient.GetSparkSettingsBeta":
				res.resp, res.err = c.dispatchGetSparkSettingsBeta(req)
			case "CapacitySettingsClient.UpdateSparkSettingsBeta":
				res.resp, res.err = c.dispatchUpdateSparkSettingsBeta(req)
			default:
				res.err = fmt.Errorf("unhandled API %s", method)
			}

		}
		select {
		case resultChan <- res:
		case <-req.Context().Done():
		}
	}()

	select {
	case <-req.Context().Done():
		return nil, req.Context().Err()
	case res := <-resultChan:
		return res.resp, res.err
	}
}

func (c *CapacitySettingsServerTransport) dispatchGetSparkSettingsBeta(req *http.Request) (*http.Response, error) {
	if c.srv.GetSparkSettingsBeta == nil {
		return nil, &nonRetriableError{errors.New("fake for method GetSparkSettingsBeta not implemented")}
	}
	const regexStr = `/v1/capacities/(?P<capacityId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/spark/settings`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 2 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	qp := req.URL.Query()
	capacityIDParam, err := url.PathUnescape(matches[regex.SubexpIndex("capacityId")])
	if err != nil {
		return nil, err
	}
	betaUnescaped, err := url.QueryUnescape(qp.Get("beta"))
	if err != nil {
		return nil, err
	}
	betaParam, err := strconv.ParseBool(betaUnescaped)
	if err != nil {
		return nil, err
	}
	respr, errRespr := c.srv.GetSparkSettingsBeta(req.Context(), capacityIDParam, betaParam, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).CapacitySparkSettings, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *CapacitySettingsServerTransport) dispatchUpdateSparkSettingsBeta(req *http.Request) (*http.Response, error) {
	if c.srv.UpdateSparkSettingsBeta == nil {
		return nil, &nonRetriableError{errors.New("fake for method UpdateSparkSettingsBeta not implemented")}
	}
	const regexStr = `/v1/capacities/(?P<capacityId>[!#&$-;=?-\[\]_a-zA-Z0-9~%@]+)/spark/settings`
	regex := regexp.MustCompile(regexStr)
	matches := regex.FindStringSubmatch(req.URL.EscapedPath())
	if len(matches) < 2 {
		return nil, fmt.Errorf("failed to parse path %s", req.URL.Path)
	}
	qp := req.URL.Query()
	body, err := server.UnmarshalRequestAsJSON[spark.UpdateCapacitySparkSettingsRequest](req)
	if err != nil {
		return nil, err
	}
	capacityIDParam, err := url.PathUnescape(matches[regex.SubexpIndex("capacityId")])
	if err != nil {
		return nil, err
	}
	betaUnescaped, err := url.QueryUnescape(qp.Get("beta"))
	if err != nil {
		return nil, err
	}
	betaParam, err := strconv.ParseBool(betaUnescaped)
	if err != nil {
		return nil, err
	}
	respr, errRespr := c.srv.UpdateSparkSettingsBeta(req.Context(), capacityIDParam, betaParam, body, nil)
	if respErr := server.GetError(errRespr, req); respErr != nil {
		return nil, respErr
	}
	respContent := server.GetResponseContent(respr)
	if !contains([]int{http.StatusOK}, respContent.HTTPStatus) {
		return nil, &nonRetriableError{fmt.Errorf("unexpected status code %d. acceptable values are http.StatusOK", respContent.HTTPStatus)}
	}
	resp, err := server.MarshalResponseAsJSON(respContent, server.GetResponse(respr).CapacitySparkSettings, req)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

// set this to conditionally intercept incoming requests to CapacitySettingsServerTransport
var capacitySettingsServerTransportInterceptor interface {
	// Do returns true if the server transport should use the returned response/error
	Do(*http.Request) (*http.Response, error, bool)
}
