// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package graphqueryset_test

import (
	"context"
	"net/http"
	"testing"

	"github.com/Azure/azure-sdk-for-go/sdk/azcore"

	azfake "github.com/Azure/azure-sdk-for-go/sdk/azcore/fake"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/to"

	"reflect"

	"github.com/stretchr/testify/suite"

	"github.com/microsoft/fabric-sdk-go/fabric"
	"github.com/microsoft/fabric-sdk-go/fabric/graphqueryset"
	"github.com/microsoft/fabric-sdk-go/fabric/graphqueryset/fake"
)

var err error

type FakeTestSuite struct {
	suite.Suite

	ctx  context.Context
	cred azcore.TokenCredential

	serverFactory *fake.ServerFactory
	clientFactory *graphqueryset.ClientFactory
}

func (testsuite *FakeTestSuite) SetupSuite() {
	testsuite.ctx = context.Background()
	testsuite.cred = &azfake.TokenCredential{}

	testsuite.serverFactory = &fake.ServerFactory{}
	testsuite.clientFactory, err = graphqueryset.NewClientFactory(testsuite.cred, nil, &fabric.ClientOptions{
		ClientOptions: azcore.ClientOptions{
			Transport: fake.NewServerFactoryTransport(testsuite.serverFactory),
		},
	})
	testsuite.Require().NoError(err, "Failed to create client factory")
}

func TestFakeTest(t *testing.T) {
	suite.Run(t, new(FakeTestSuite))
}

func (testsuite *FakeTestSuite) TestItems_ListGraphQuerySets() {
	// From example
	ctx := runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"List GraphQuerySets in workspace example"},
	})
	var exampleWorkspaceID string
	exampleWorkspaceID = "cfafbeb1-8037-4d0c-896e-a46fb27ff229"

	exampleRes := graphqueryset.GraphQuerySets{
		Value: []graphqueryset.GraphQuerySet{
			{
				Type:        to.Ptr(graphqueryset.ItemTypeGraphQuerySet),
				Description: to.Ptr("A GraphQuerySet description."),
				DisplayName: to.Ptr("GraphQuerySet Name 1"),
				ID:          to.Ptr("3546052c-ae64-4526-b1a8-52af7761426f"),
				WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
			},
			{
				Type:        to.Ptr(graphqueryset.ItemTypeGraphQuerySet),
				Description: to.Ptr("A GraphQuerySet description."),
				DisplayName: to.Ptr("GraphQuerySet Name 2"),
				ID:          to.Ptr("f697fb63-abd4-4399-9548-be7e3c3c0dac"),
				WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
			}},
	}

	testsuite.serverFactory.ItemsServer.NewListGraphQuerySetsPager = func(workspaceID string, options *graphqueryset.ItemsClientListGraphQuerySetsOptions) (resp azfake.PagerResponder[graphqueryset.ItemsClientListGraphQuerySetsResponse]) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		resp = azfake.PagerResponder[graphqueryset.ItemsClientListGraphQuerySetsResponse]{}
		resp.AddPage(http.StatusOK, graphqueryset.ItemsClientListGraphQuerySetsResponse{GraphQuerySets: exampleRes}, nil)
		return
	}

	client := testsuite.clientFactory.NewItemsClient()
	pager := client.NewListGraphQuerySetsPager(exampleWorkspaceID, &graphqueryset.ItemsClientListGraphQuerySetsOptions{ContinuationToken: nil})
	for pager.More() {
		nextResult, err := pager.NextPage(ctx)
		testsuite.Require().NoError(err, "Failed to advance page for example ")
		testsuite.Require().True(reflect.DeepEqual(exampleRes, nextResult.GraphQuerySets))
		if err == nil {
			break
		}
	}
}

func (testsuite *FakeTestSuite) TestItems_CreateGraphQuerySet() {
	// From example
	ctx := runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"Create a GraphQuerySet example"},
	})
	var exampleWorkspaceID string
	var exampleCreateGraphQuerySetRequest graphqueryset.CreateGraphQuerySetRequest
	exampleWorkspaceID = "cfafbeb1-8037-4d0c-896e-a46fb27ff229"
	exampleCreateGraphQuerySetRequest = graphqueryset.CreateGraphQuerySetRequest{
		Description: to.Ptr("A GraphQuerySet description."),
		DisplayName: to.Ptr("GraphQuerySet 1"),
	}

	testsuite.serverFactory.ItemsServer.BeginCreateGraphQuerySet = func(ctx context.Context, workspaceID string, createGraphQuerySetRequest graphqueryset.CreateGraphQuerySetRequest, options *graphqueryset.ItemsClientBeginCreateGraphQuerySetOptions) (resp azfake.PollerResponder[graphqueryset.ItemsClientCreateGraphQuerySetResponse], errResp azfake.ErrorResponder) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		testsuite.Require().True(reflect.DeepEqual(exampleCreateGraphQuerySetRequest, createGraphQuerySetRequest))
		resp = azfake.PollerResponder[graphqueryset.ItemsClientCreateGraphQuerySetResponse]{}
		resp.SetTerminalResponse(http.StatusCreated, graphqueryset.ItemsClientCreateGraphQuerySetResponse{}, nil)
		return
	}

	client := testsuite.clientFactory.NewItemsClient()
	poller, err := client.BeginCreateGraphQuerySet(ctx, exampleWorkspaceID, exampleCreateGraphQuerySetRequest, nil)
	testsuite.Require().NoError(err, "Failed to get result for example ")
	_, err = poller.PollUntilDone(ctx, nil)
	testsuite.Require().NoError(err, "Failed to get LRO result for example ")

	// From example
	ctx = runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"Create a GraphQuerySet with public definition example"},
	})
	exampleWorkspaceID = "cfafbeb1-8037-4d0c-896e-a46fb27ff229"
	exampleCreateGraphQuerySetRequest = graphqueryset.CreateGraphQuerySetRequest{
		Description: to.Ptr("A GraphQuerySet description."),
		Definition: &graphqueryset.PublicDefinition{
			Format: to.Ptr("json"),
			Parts: []graphqueryset.PublicDefinitionPart{
				{
					Path:        to.Ptr("graphQuerySet.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphqueryset.PayloadTypeInlineBase64),
				}},
		},
		DisplayName: to.Ptr("GraphQuerySet 1"),
	}

	testsuite.serverFactory.ItemsServer.BeginCreateGraphQuerySet = func(ctx context.Context, workspaceID string, createGraphQuerySetRequest graphqueryset.CreateGraphQuerySetRequest, options *graphqueryset.ItemsClientBeginCreateGraphQuerySetOptions) (resp azfake.PollerResponder[graphqueryset.ItemsClientCreateGraphQuerySetResponse], errResp azfake.ErrorResponder) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		testsuite.Require().True(reflect.DeepEqual(exampleCreateGraphQuerySetRequest, createGraphQuerySetRequest))
		resp = azfake.PollerResponder[graphqueryset.ItemsClientCreateGraphQuerySetResponse]{}
		resp.SetTerminalResponse(http.StatusCreated, graphqueryset.ItemsClientCreateGraphQuerySetResponse{}, nil)
		return
	}

	poller, err = client.BeginCreateGraphQuerySet(ctx, exampleWorkspaceID, exampleCreateGraphQuerySetRequest, nil)
	testsuite.Require().NoError(err, "Failed to get result for example ")
	_, err = poller.PollUntilDone(ctx, nil)
	testsuite.Require().NoError(err, "Failed to get LRO result for example ")
}

func (testsuite *FakeTestSuite) TestItems_GetGraphQuerySet() {
	// From example
	ctx := runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"Get a GraphQuerySet example"},
	})
	var exampleWorkspaceID string
	var exampleGraphQuerySetID string
	exampleWorkspaceID = "f089354e-8366-4e18-aea3-4cb4a3a50b48"
	exampleGraphQuerySetID = "41ce06d1-d81b-4ea0-bc6d-2ce3dd2f8e87"

	exampleRes := graphqueryset.GraphQuerySet{
		Type:        to.Ptr(graphqueryset.ItemTypeGraphQuerySet),
		Description: to.Ptr("A GraphQuerySet description."),
		DisplayName: to.Ptr("GraphQuerySet 1"),
		ID:          to.Ptr("5b218778-e7a5-4d73-8187-f10824047715"),
		WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
	}

	testsuite.serverFactory.ItemsServer.GetGraphQuerySet = func(ctx context.Context, workspaceID string, graphQuerySetID string, options *graphqueryset.ItemsClientGetGraphQuerySetOptions) (resp azfake.Responder[graphqueryset.ItemsClientGetGraphQuerySetResponse], errResp azfake.ErrorResponder) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		testsuite.Require().Equal(exampleGraphQuerySetID, graphQuerySetID)
		resp = azfake.Responder[graphqueryset.ItemsClientGetGraphQuerySetResponse]{}
		resp.SetResponse(http.StatusOK, graphqueryset.ItemsClientGetGraphQuerySetResponse{GraphQuerySet: exampleRes}, nil)
		return
	}

	client := testsuite.clientFactory.NewItemsClient()
	res, err := client.GetGraphQuerySet(ctx, exampleWorkspaceID, exampleGraphQuerySetID, nil)
	testsuite.Require().NoError(err, "Failed to get result for example ")
	testsuite.Require().True(reflect.DeepEqual(exampleRes, res.GraphQuerySet))
}

func (testsuite *FakeTestSuite) TestItems_UpdateGraphQuerySet() {
	// From example
	ctx := runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"Update a GraphQuerySet example"},
	})
	var exampleWorkspaceID string
	var exampleGraphQuerySetID string
	var exampleUpdateGraphQuerySetRequest graphqueryset.UpdateGraphQuerySetRequest
	exampleWorkspaceID = "cfafbeb1-8037-4d0c-896e-a46fb27ff229"
	exampleGraphQuerySetID = "5b218778-e7a5-4d73-8187-f10824047715"
	exampleUpdateGraphQuerySetRequest = graphqueryset.UpdateGraphQuerySetRequest{
		Description: to.Ptr("GraphQuerySet's New description"),
		DisplayName: to.Ptr("GraphQuerySet's New name"),
	}

	exampleRes := graphqueryset.GraphQuerySet{
		Type:        to.Ptr(graphqueryset.ItemTypeGraphQuerySet),
		Description: to.Ptr("GraphQuerySet's New description"),
		DisplayName: to.Ptr("GraphQuerySet's New name"),
		ID:          to.Ptr("5b218778-e7a5-4d73-8187-f10824047715"),
		WorkspaceID: to.Ptr("cfafbeb1-8037-4d0c-896e-a46fb27ff229"),
	}

	testsuite.serverFactory.ItemsServer.UpdateGraphQuerySet = func(ctx context.Context, workspaceID string, graphQuerySetID string, updateGraphQuerySetRequest graphqueryset.UpdateGraphQuerySetRequest, options *graphqueryset.ItemsClientUpdateGraphQuerySetOptions) (resp azfake.Responder[graphqueryset.ItemsClientUpdateGraphQuerySetResponse], errResp azfake.ErrorResponder) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		testsuite.Require().Equal(exampleGraphQuerySetID, graphQuerySetID)
		testsuite.Require().True(reflect.DeepEqual(exampleUpdateGraphQuerySetRequest, updateGraphQuerySetRequest))
		resp = azfake.Responder[graphqueryset.ItemsClientUpdateGraphQuerySetResponse]{}
		resp.SetResponse(http.StatusOK, graphqueryset.ItemsClientUpdateGraphQuerySetResponse{GraphQuerySet: exampleRes}, nil)
		return
	}

	client := testsuite.clientFactory.NewItemsClient()
	res, err := client.UpdateGraphQuerySet(ctx, exampleWorkspaceID, exampleGraphQuerySetID, exampleUpdateGraphQuerySetRequest, nil)
	testsuite.Require().NoError(err, "Failed to get result for example ")
	testsuite.Require().True(reflect.DeepEqual(exampleRes, res.GraphQuerySet))
}

func (testsuite *FakeTestSuite) TestItems_DeleteGraphQuerySet() {
	// From example
	ctx := runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"Delete a GraphQuerySet example"},
	})
	var exampleWorkspaceID string
	var exampleGraphQuerySetID string
	exampleWorkspaceID = "cfafbeb1-8037-4d0c-896e-a46fb27ff229"
	exampleGraphQuerySetID = "5b218778-e7a5-4d73-8187-f10824047715"

	testsuite.serverFactory.ItemsServer.DeleteGraphQuerySet = func(ctx context.Context, workspaceID string, graphQuerySetID string, options *graphqueryset.ItemsClientDeleteGraphQuerySetOptions) (resp azfake.Responder[graphqueryset.ItemsClientDeleteGraphQuerySetResponse], errResp azfake.ErrorResponder) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		testsuite.Require().Equal(exampleGraphQuerySetID, graphQuerySetID)
		resp = azfake.Responder[graphqueryset.ItemsClientDeleteGraphQuerySetResponse]{}
		resp.SetResponse(http.StatusOK, graphqueryset.ItemsClientDeleteGraphQuerySetResponse{}, nil)
		return
	}

	client := testsuite.clientFactory.NewItemsClient()
	_, err = client.DeleteGraphQuerySet(ctx, exampleWorkspaceID, exampleGraphQuerySetID, nil)
	testsuite.Require().NoError(err, "Failed to get result for example ")
}

func (testsuite *FakeTestSuite) TestItems_GetGraphQuerySetDefinition() {
	// From example
	ctx := runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"Get a GraphQuerySet public definition example"},
	})
	var exampleWorkspaceID string
	var exampleGraphQuerySetID string
	exampleWorkspaceID = "6e335e92-a2a2-4b5a-970a-bd6a89fbb765"
	exampleGraphQuerySetID = "cfafbeb1-8037-4d0c-896e-a46fb27ff229"

	exampleRes := graphqueryset.DefinitionResponse{
		Definition: &graphqueryset.PublicDefinition{
			Format: to.Ptr("json"),
			Parts: []graphqueryset.PublicDefinitionPart{
				{
					Path:        to.Ptr("graphQuerySet.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphqueryset.PayloadTypeInlineBase64),
				}},
		},
	}

	testsuite.serverFactory.ItemsServer.BeginGetGraphQuerySetDefinition = func(ctx context.Context, workspaceID string, graphQuerySetID string, options *graphqueryset.ItemsClientBeginGetGraphQuerySetDefinitionOptions) (resp azfake.PollerResponder[graphqueryset.ItemsClientGetGraphQuerySetDefinitionResponse], errResp azfake.ErrorResponder) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		testsuite.Require().Equal(exampleGraphQuerySetID, graphQuerySetID)
		resp = azfake.PollerResponder[graphqueryset.ItemsClientGetGraphQuerySetDefinitionResponse]{}
		resp.SetTerminalResponse(http.StatusOK, graphqueryset.ItemsClientGetGraphQuerySetDefinitionResponse{DefinitionResponse: exampleRes}, nil)
		return
	}

	client := testsuite.clientFactory.NewItemsClient()
	poller, err := client.BeginGetGraphQuerySetDefinition(ctx, exampleWorkspaceID, exampleGraphQuerySetID, &graphqueryset.ItemsClientBeginGetGraphQuerySetDefinitionOptions{Format: nil})
	testsuite.Require().NoError(err, "Failed to get result for example ")
	res, err := poller.PollUntilDone(ctx, nil)
	testsuite.Require().NoError(err, "Failed to get LRO result for example ")
	testsuite.Require().True(reflect.DeepEqual(exampleRes, res.DefinitionResponse))
}

func (testsuite *FakeTestSuite) TestItems_UpdateGraphQuerySetDefinition() {
	// From example
	ctx := runtime.WithHTTPHeader(testsuite.ctx, map[string][]string{
		"example-id": {"Update a GraphQuerySet public definition example"},
	})
	var exampleWorkspaceID string
	var exampleGraphQuerySetID string
	var exampleUpdateGraphQuerySetDefinitionRequest graphqueryset.UpdateGraphQuerySetDefinitionRequest
	exampleWorkspaceID = "cfafbeb1-8037-4d0c-896e-a46fb27ff229"
	exampleGraphQuerySetID = "5b218778-e7a5-4d73-8187-f10824047715"
	exampleUpdateGraphQuerySetDefinitionRequest = graphqueryset.UpdateGraphQuerySetDefinitionRequest{
		Definition: &graphqueryset.PublicDefinition{
			Format: to.Ptr("json"),
			Parts: []graphqueryset.PublicDefinitionPart{
				{
					Path:        to.Ptr("graphQuerySet.json"),
					Payload:     to.Ptr("eyJleGVjdXRhYmxlRm..OWRmNDhhY2ZmZTgifQ=="),
					PayloadType: to.Ptr(graphqueryset.PayloadTypeInlineBase64),
				}},
		},
	}

	testsuite.serverFactory.ItemsServer.BeginUpdateGraphQuerySetDefinition = func(ctx context.Context, workspaceID string, graphQuerySetID string, updateGraphQuerySetDefinitionRequest graphqueryset.UpdateGraphQuerySetDefinitionRequest, options *graphqueryset.ItemsClientBeginUpdateGraphQuerySetDefinitionOptions) (resp azfake.PollerResponder[graphqueryset.ItemsClientUpdateGraphQuerySetDefinitionResponse], errResp azfake.ErrorResponder) {
		testsuite.Require().Equal(exampleWorkspaceID, workspaceID)
		testsuite.Require().Equal(exampleGraphQuerySetID, graphQuerySetID)
		testsuite.Require().True(reflect.DeepEqual(exampleUpdateGraphQuerySetDefinitionRequest, updateGraphQuerySetDefinitionRequest))
		resp = azfake.PollerResponder[graphqueryset.ItemsClientUpdateGraphQuerySetDefinitionResponse]{}
		resp.SetTerminalResponse(http.StatusOK, graphqueryset.ItemsClientUpdateGraphQuerySetDefinitionResponse{}, nil)
		return
	}

	client := testsuite.clientFactory.NewItemsClient()
	poller, err := client.BeginUpdateGraphQuerySetDefinition(ctx, exampleWorkspaceID, exampleGraphQuerySetID, exampleUpdateGraphQuerySetDefinitionRequest, &graphqueryset.ItemsClientBeginUpdateGraphQuerySetDefinitionOptions{UpdateMetadata: to.Ptr(true)})
	testsuite.Require().NoError(err, "Failed to get result for example ")
	_, err = poller.PollUntilDone(ctx, nil)
	testsuite.Require().NoError(err, "Failed to get LRO result for example ")
}
