// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT License. See LICENSE in the project root for license information.
// Code generated by Microsoft (R) AutoRest Code Generator. DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// SPDX-License-Identifier: MIT

package notebook

import "time"

// CreateNotebookRequest - Create notebook request payload.
type CreateNotebookRequest struct {
	// REQUIRED; The notebook display name. The display name must follow naming rules according to item type.
	DisplayName *string

	// The notebook public definition.
	Definition *Definition

	// The notebook description. Maximum length is 256 characters.
	Description *string

	// The folder ID. If not specified or null, the notebook is created with the workspace as its folder.
	FolderID *string

	// The sensitivity label settings for the notebook.
	SensitivityLabelSettings *SensitivityLabelSettings
}

// DataWarehouseNotebookComputeDetails - Data warehouse notebook compute details.
type DataWarehouseNotebookComputeDetails struct {
	// The data warehouse notebook monitoring infomation.
	MonitoringInfo *DataWarehouseNotebookMonitoringInfo

	// The primary warehouse.
	PrimaryWarehouse *ItemReferenceByID
}

// DataWarehouseNotebookJobInstanceProperties - Data warehouse notebook job instance properties.
type DataWarehouseNotebookJobInstanceProperties struct {
	// REQUIRED; The execution engine for the job instance.
	Compute *ComputeType

	// REQUIRED; The details of data warehouse notebook job instance.
	ComputeDetails *DataWarehouseNotebookComputeDetails

	// User defined exit value in notebook. Refer to this article [/fabric/data-engineering/notebook-utilities#exit-a-notebook]
	// for more details on how to set the notebook exit value.
	ExitValue *string
}

// GetJobInstanceProperties implements the JobInstancePropertiesClassification interface for type DataWarehouseNotebookJobInstanceProperties.
func (d *DataWarehouseNotebookJobInstanceProperties) GetJobInstanceProperties() *JobInstanceProperties {
	return &JobInstanceProperties{
		Compute:   d.Compute,
		ExitValue: d.ExitValue,
	}
}

// DataWarehouseNotebookMonitoringInfo - Data Warehouse notebook monitoring information.
type DataWarehouseNotebookMonitoringInfo struct {
	// Notebook execution snapshot url.
	ExecutionSnapshotURL *string
}

// Definition - Notebook public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/notebook-definition]
// for more details on the structure of the Notebook definition.
type Definition struct {
	// REQUIRED; A list of definition parts.
	Parts []DefinitionPart

	// The format of the Notebook definition. Supported format: ipynb and fabricGitSource. If no format is provided, fabricGitSource
	// is used.
	Format *string
}

// DefinitionPart - Notebook definition part object.
type DefinitionPart struct {
	// The notebook part path. Supported notebook content extensions: .ipynb for ipynb format; .py, .scala, .r, .sql for fabricGitSource
	// format.
	Path *string

	// The notebook part payload.
	Payload *string

	// The payload type.
	PayloadType *PayloadType
}

// DefinitionResponse - Notebook public definition response.
type DefinitionResponse struct {
	// READ-ONLY; Notebook public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/notebook-definition]
	// for more details on the structure of the Notebook definition.
	Definition *Definition
}

// Duration - A duration.
type Duration struct {
	// REQUIRED; The unit of time for the duration. Additional duration types may be added over time.
	TimeUnit *TimeUnit

	// REQUIRED; The number of timeUnits in the duration.
	Value *float32
}

// EntireTenantPrincipal - Represents a tenant principal
type EntireTenantPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type EntireTenantPrincipal.
func (e *EntireTenantPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: e.DisplayName,
		ID:          e.ID,
		Type:        e.Type,
	}
}

// ErrorRelatedResource - The error related resource details object.
type ErrorRelatedResource struct {
	// READ-ONLY; The resource ID that's involved in the error.
	ResourceID *string

	// READ-ONLY; The type of the resource that's involved in the error.
	ResourceType *string
}

// ErrorResponse - The error response.
type ErrorResponse struct {
	// READ-ONLY; A specific identifier that provides information about an error condition, allowing for standardized communication
	// between our service and its users.
	ErrorCode *string

	// READ-ONLY; A human readable representation of the error.
	Message *string

	// READ-ONLY; List of additional error details.
	MoreDetails []ErrorResponseDetails

	// READ-ONLY; The error related resource details.
	RelatedResource *ErrorRelatedResource

	// READ-ONLY; ID of the request associated with the error.
	RequestID *string
}

// ErrorResponseDetails - The error response details.
type ErrorResponseDetails struct {
	// READ-ONLY; A specific identifier that provides information about an error condition, allowing for standardized communication
	// between our service and its users.
	ErrorCode *string

	// READ-ONLY; A human readable representation of the error.
	Message *string

	// READ-ONLY; The error related resource details.
	RelatedResource *ErrorRelatedResource
}

// GroupPrincipal - Represents a security group.
type GroupPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Group specific details. Applicable when the principal type is Group.
	GroupDetails *GroupPrincipalGroupDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type GroupPrincipal.
func (g *GroupPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: g.DisplayName,
		ID:          g.ID,
		Type:        g.Type,
	}
}

// GroupPrincipalGroupDetails - Group specific details. Applicable when the principal type is Group.
type GroupPrincipalGroupDetails struct {
	// The type of the group. Additional group types may be added over time.
	GroupType *GroupType
}

// HighConcurrencyModeOptions - High concurrency mode options.
type HighConcurrencyModeOptions struct {
	// REQUIRED; The status of the high concurrency mode. False - Disabled, true - Enabled.
	Enabled *bool

	// Setting the session tag instructs Spark to reuse existing Spark sessions which minimizes startup time. Arbitrary string
	// values can be used for the session tag. If no session exists, a new session is
	// created using the tag value.
	SessionTag *string
}

// HighConcurrencyModeStatus - Spark notebook high concurrency mode status.
type HighConcurrencyModeStatus struct {
	// A new created session or attach to existing sessions.
	SessionSource *SessionSource

	// Session tag value to execute the notebook in a shared Spark session.
	SessionTag *string
}

// InstancePool - The instance pool.
type InstancePool struct {
	// Instance pool ID.
	ID *string

	// Instance pool name.
	Name *string

	// Instance pool type.
	Type *CustomPoolType
}

// ItemReference - An item reference object.
type ItemReference struct {
	// REQUIRED; The item reference type.
	ReferenceType *ItemReferenceType
}

// GetItemReference implements the ItemReferenceClassification interface for type ItemReference.
func (i *ItemReference) GetItemReference() *ItemReference { return i }

// ItemReferenceByID - An item reference by ID object.
type ItemReferenceByID struct {
	// REQUIRED; The ID of the item.
	ItemID *string

	// REQUIRED; The item reference type.
	ReferenceType *ItemReferenceType

	// REQUIRED; The workspace ID of the item.
	WorkspaceID *string
}

// GetItemReference implements the ItemReferenceClassification interface for type ItemReferenceByID.
func (i *ItemReferenceByID) GetItemReference() *ItemReference {
	return &ItemReference{
		ReferenceType: i.ReferenceType,
	}
}

// ItemReferenceByVariable - An item reference by variable.
type ItemReferenceByVariable struct {
	// REQUIRED; The item reference type.
	ReferenceType *ItemReferenceType

	// REQUIRED; A variable reference string that specifies the Variable Library and the variable name inside it. Format: $(/**/_VarLibrary_/_VarName_)
	// for a Variable Library named VarLibrary and a variable named
	// VarName.
	VariableReference *string
}

// GetItemReference implements the ItemReferenceClassification interface for type ItemReferenceByVariable.
func (i *ItemReferenceByVariable) GetItemReference() *ItemReference {
	return &ItemReference{
		ReferenceType: i.ReferenceType,
	}
}

// ItemTag - Represents a tag applied on an item.
type ItemTag struct {
	// REQUIRED; The name of the tag.
	DisplayName *string

	// REQUIRED; The tag ID.
	ID *string
}

// JobInstance - An object representing notebook job instance.
type JobInstance struct {
	// Job end time in UTC
	EndTimeUTC *string

	// Job instance Id
	ID *string

	// The item job invoke type. Additional invokeTypes may be added over time.
	InvokeType *InvokeType

	// Item Id
	ItemID *string

	// Job type
	JobType *string

	// Notebook job instance properties.
	Properties JobInstancePropertiesClassification

	// Root activity id to trace requests across services
	RootActivityID *string

	// Job start time in UTC
	StartTimeUTC *string

	// The item job status. Additional statuses may be added over time.
	Status *ItemJobStatus

	// READ-ONLY; Error response when job is failed
	FailureReason *ErrorResponse
}

// JobInstanceProperties - Notebook job instance properties.
type JobInstanceProperties struct {
	// REQUIRED; The execution engine for the job instance.
	Compute *ComputeType

	// User defined exit value in notebook. Refer to this article [/fabric/data-engineering/notebook-utilities#exit-a-notebook]
	// for more details on how to set the notebook exit value.
	ExitValue *string
}

// GetJobInstanceProperties implements the JobInstancePropertiesClassification interface for type JobInstanceProperties.
func (j *JobInstanceProperties) GetJobInstanceProperties() *JobInstanceProperties { return j }

// JupyterNotebookComputeConfiguration - Jupyter notebook compute configuration.
type JupyterNotebookComputeConfiguration struct {
	// Environment to be used in this session.
	AttachedEnvironment *ItemReferenceByID

	// Default lakehouse to be used in this session.
	DefaultLakehouse *ItemReferenceByID

	// Mount points to be used in this session.
	MountPoints []MountPoint

	// The name of this session.
	Name *string

	// The number of cores that this job can consume. Must be one of the following values: 2, 4, 8, 16, 32, 64.
	NumCores *int32
}

// JupyterNotebookComputeDetails - Jupyter notebook compute details.
type JupyterNotebookComputeDetails struct {
	// The jupyter session id.
	ActivityID *string

	// The jupyter notebook monitoring infomation.
	MonitoringInfo *JupyterNotebookMonitoringInfo
}

// JupyterNotebookJobInstanceProperties - Jupyter notebook job instance properties.
type JupyterNotebookJobInstanceProperties struct {
	// REQUIRED; The execution engine for the job instance.
	Compute *ComputeType

	// REQUIRED; The details of jupyter notebook job instance.
	ComputeDetails *JupyterNotebookComputeDetails

	// User defined exit value in notebook. Refer to this article [/fabric/data-engineering/notebook-utilities#exit-a-notebook]
	// for more details on how to set the notebook exit value.
	ExitValue *string
}

// GetJobInstanceProperties implements the JobInstancePropertiesClassification interface for type JupyterNotebookJobInstanceProperties.
func (j *JupyterNotebookJobInstanceProperties) GetJobInstanceProperties() *JobInstanceProperties {
	return &JobInstanceProperties{
		Compute:   j.Compute,
		ExitValue: j.ExitValue,
	}
}

// JupyterNotebookMonitoringInfo - Jupyter notebook monitoring information.
type JupyterNotebookMonitoringInfo struct {
	// Notebook execution snapshot url.
	ExecutionSnapshotURL *string
}

// LivySession - The livy session response
type LivySession struct {
	// Current attempt number.
	AttemptNumber *int32

	// Reason for the job cancellation.
	CancellationReason *string

	// ID of the capacity.
	CapacityID *string

	// ID of the consumer.
	ConsumerID PrincipalClassification

	// ID of the item creator. When isHighConcurrency is set to true this value might be different than itemId.
	CreatorItem *ItemReferenceByID

	// The number of CPU cores allocated to the Spark driver. Controls how much parallel processing the driver can handle.
	DriverCores *int32

	// The amount of memory (in GB) assigned to the Spark driver process. Affects the driver's ability to handle job coordination
	// and metadata.
	DriverMemory *int32

	// Sets the maximum number of executors that Spark's dynamic allocation can scale up to during job execution.
	DynamicAllocationMaxExecutors *int32

	// Timestamp when the job ended in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	EndDateTime *time.Time

	// The number of CPU cores allocated to each Spark executor. Determines how many tasks each executor can run in parallel.
	ExecutorCores any

	// The amount of memory (in GB) assigned to each Spark executor process. Impacts how much data can be processed in memory
	// per executor.
	ExecutorMemory *int32

	// Flag indicating whether dynamic allocation is enabled for the Spark job.
	IsDynamicAllocationEnabled *bool

	// Flag indicating high concurrency.
	IsHighConcurrency *bool

	// ID of the item.
	Item *ItemReferenceByID

	// Name of the item.
	ItemName *string

	// The item type.
	ItemType *LivySessionItemType

	// ID of the job instance.
	JobInstanceID *string

	// Current state of the job.
	JobType *JobType

	// ID of the Livy session or Livy batch.
	LivyID *string

	// Name of the Livy session or Livy batch.
	LivyName *string

	// The URI used to retrieve all Livy sessions for a given item.
	LivySessionItemResourceURI *string

	// Maximum number of attempts.
	MaxNumberOfAttempts *int32

	// The total number of executors requested for the Spark job. Controls the parallelism and scalability of the job.
	NumExecutors *int32

	// Name of the operation. Possible values include: Notebook run, Notebook HC run and Notebook pipeline run.
	OperationName *string

	// Origin of the job.
	Origin *Origin

	// Duration for which the job was queued.
	QueuedDuration *Duration

	// Time it took the job to run.
	RunningDuration *Duration

	// The fabric runtime version.
	RuntimeVersion *string

	// A Spark application ID is a unique identifier assigned to each Apache Spark application. It also appears in the Spark UI.
	SparkApplicationID *string

	// Timestamp when the job started in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	StartDateTime *time.Time

	// Current state of the job.
	State *State

	// Timestamp when the job was submitted in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	SubmittedDateTime *time.Time

	// ID of the submitter.
	Submitter PrincipalClassification

	// Total duration of the job.
	TotalDuration *Duration
}

// LivySessions - A paginated list of livy sessions.
type LivySessions struct {
	// REQUIRED; A list of livy sessions.
	Value []LivySession

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// MountPoint - The storage mount point.
type MountPoint struct {
	// REQUIRED; The local path that to mount the remote storage to.
	MountPointPath *string

	// REQUIRED; Source storage abfss path.
	Source *string
}

// Notebook - A notebook object.
type Notebook struct {
	// REQUIRED; The item type.
	Type *ItemType

	// The item description.
	Description *string

	// The item display name.
	DisplayName *string

	// READ-ONLY; The folder ID.
	FolderID *string

	// READ-ONLY; The item ID.
	ID *string

	// READ-ONLY; The item sensitivity label.
	SensitivityLabel *SensitivityLabel

	// READ-ONLY; List of applied tags.
	Tags []ItemTag

	// READ-ONLY; The workspace ID.
	WorkspaceID *string
}

// Notebooks - A list of notebooks.
type Notebooks struct {
	// REQUIRED; A list of notebooks.
	Value []Notebook

	// The token for the next result set batch. If there are no more records, it's removed from the response.
	ContinuationToken *string

	// The URI of the next result set batch. If there are no more records, it's removed from the response.
	ContinuationURI *string
}

// Parameter - An item job parameter.
type Parameter struct {
	// REQUIRED; The parameter name, specified by the caller, must be unique (case-insensitive check) and no longer than 256 characters.
	Name *string

	// REQUIRED; The parameter type.
	Type *ItemJobParameterType

	// REQUIRED; The parameter value based on the parameter type.
	Value any
}

// Principal - Represents an identity or a Microsoft Entra group.
type Principal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type Principal.
func (p *Principal) GetPrincipal() *Principal { return p }

// RunDataWarehouseNotebookExecutionData - Data Warehouse notebook execution data. This compute type does not support compute
// configuration.
type RunDataWarehouseNotebookExecutionData struct {
	// REQUIRED; The execution engine for the job instance. This value needs to match the language of the notebook.
	Compute *ComputeType
}

// GetRunNotebookExecutionData implements the RunNotebookExecutionDataClassification interface for type RunDataWarehouseNotebookExecutionData.
func (r *RunDataWarehouseNotebookExecutionData) GetRunNotebookExecutionData() *RunNotebookExecutionData {
	return &RunNotebookExecutionData{
		Compute: r.Compute,
	}
}

// RunJupyterNotebookExecutionData - Jupyter notebook execution data.
type RunJupyterNotebookExecutionData struct {
	// REQUIRED; The execution engine for the job instance. This value needs to match the language of the notebook.
	Compute *ComputeType

	// The Jupyter notebook execution configuration.
	ComputeConfiguration *JupyterNotebookComputeConfiguration
}

// GetRunNotebookExecutionData implements the RunNotebookExecutionDataClassification interface for type RunJupyterNotebookExecutionData.
func (r *RunJupyterNotebookExecutionData) GetRunNotebookExecutionData() *RunNotebookExecutionData {
	return &RunNotebookExecutionData{
		Compute: r.Compute,
	}
}

// RunNotebookExecutionData - Execution data for the notebook run.
type RunNotebookExecutionData struct {
	// REQUIRED; The execution engine for the job instance. This value needs to match the language of the notebook.
	Compute *ComputeType
}

// GetRunNotebookExecutionData implements the RunNotebookExecutionDataClassification interface for type RunNotebookExecutionData.
func (r *RunNotebookExecutionData) GetRunNotebookExecutionData() *RunNotebookExecutionData { return r }

// RunNotebookRequest - Run notebook request with executionData.
type RunNotebookRequest struct {
	// Optional. The notebook configurations used during execution.
	ExecutionData RunNotebookExecutionDataClassification

	// The parameter list for run on-demand job request. Per-run, user-defined inputs to tailor this invocation. Note: parameter
	// names are case-insensitive, but the casing must match the parameter name used
	// in the code cell.
	Parameters []Parameter
}

// RunSparkNotebookExecutionData - Spark notebook execution data.
type RunSparkNotebookExecutionData struct {
	// REQUIRED; The execution engine for the job instance. This value needs to match the language of the notebook.
	Compute *ComputeType

	// The Spark notebook execution configuration.
	ComputeConfiguration *SparkNotebookComputeConfiguration
}

// GetRunNotebookExecutionData implements the RunNotebookExecutionDataClassification interface for type RunSparkNotebookExecutionData.
func (r *RunSparkNotebookExecutionData) GetRunNotebookExecutionData() *RunNotebookExecutionData {
	return &RunNotebookExecutionData{
		Compute: r.Compute,
	}
}

// SensitivityLabel - Represents a sensitivity label applied to an item.
type SensitivityLabel struct {
	// REQUIRED; The sensitivity label ID.
	ID *string
}

// SensitivityLabelSettings - The sensitivity label settings.
type SensitivityLabelSettings struct {
	// REQUIRED; The sensitivity label ID.
	LabelID *string

	// The strategy for applying the sensitivity label.
	SensitivityLabelApplyStrategy *SensitivityLabelApplyStrategy
}

// ServicePrincipal - Represents a Microsoft Entra service principal.
type ServicePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; Service principal specific details. Applicable when the principal type is ServicePrincipal.
	ServicePrincipalDetails *ServicePrincipalDetails
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipal.
func (s *ServicePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalDetails - Service principal specific details. Applicable when the principal type is ServicePrincipal.
type ServicePrincipalDetails struct {
	// READ-ONLY; The service principal's Microsoft Entra AppId.
	AADAppID *string
}

// ServicePrincipalProfilePrincipal - Represents a service principal profile.
type ServicePrincipalProfilePrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// Service principal profile details. Applicable when the principal type is ServicePrincipalProfile.
	ServicePrincipalProfileDetails *ServicePrincipalProfilePrincipalServicePrincipalProfileDetails

	// READ-ONLY; The principal's display name.
	DisplayName *string
}

// GetPrincipal implements the PrincipalClassification interface for type ServicePrincipalProfilePrincipal.
func (s *ServicePrincipalProfilePrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: s.DisplayName,
		ID:          s.ID,
		Type:        s.Type,
	}
}

// ServicePrincipalProfilePrincipalServicePrincipalProfileDetails - Service principal profile details. Applicable when the
// principal type is ServicePrincipalProfile.
type ServicePrincipalProfilePrincipalServicePrincipalProfileDetails struct {
	// The service principal profile's parent principal.
	ParentPrincipal PrincipalClassification
}

// SparkNotebookActivityDetails - Spark notebook livy session details.
type SparkNotebookActivityDetails struct {
	// Reason for the job cancellation.
	CancellationReason *string

	// ID of the capacity.
	CapacityID *string

	// ID of the item creator. When isHighConcurrency is set to true this value might be different than itemId.
	CreatorItem *ItemReferenceByID

	// Timestamp when the job ended in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	EndDateTime *time.Time

	// Flag indicating high concurrency.
	IsHighConcurrency *bool

	// Name of the item.
	ItemName *string

	// Current state of the job.
	JobType *JobType

	// Name of the Livy session.
	LivyName *string

	// Name of the operation. Possible values include: Notebook run, Notebook HC run and Notebook pipeline run.
	OperationName *string

	// The fabric runtime version.
	RuntimeVersion *string

	// A Spark application ID is a unique identifier assigned to each Apache Spark application. It also appears in the Spark UI.
	SparkApplicationID *string

	// Timestamp when the job started in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	StartDateTime *time.Time

	// Timestamp when the job was submitted in UTC, using the YYYY-MM-DDTHH:mm:ssZ format.
	SubmittedDateTime *time.Time
}

// SparkNotebookComputeConfiguration - Spark notebook compute configuration.
type SparkNotebookComputeConfiguration struct {
	// The list of abfs path of archives to be used in this session. Archives to be extracted into the working directory of each
	// executor. .jar, .tar.gz, .tgz and .zip are supported. You can specify the
	// directory name to unpack via adding # after the file name to unpack, for example, file.zip#directory.
	Archives []string

	// Environment to be used in this session.
	AttachedEnvironment *ItemReferenceByID

	// Default lakehouse to be used in this session.
	DefaultLakehouse *ItemReferenceByID

	// Spark driver core. Must be one of the following values: 4, 8, 16, 32, 64.
	DriverCores *int32

	// Spark driver memory.
	DriverMemory *CustomPoolMemory

	// Spark executor core. Must be one of the following values: 4, 8, 16, 32, 64.
	ExecutorCores *int32

	// Spark executor memory.
	ExecutorMemory *CustomPoolMemory

	// The list of abfs path of files to be used in this session. Files to be placed in the working directory of each executor.
	Files []string

	// High concurrency mode options.
	HighConcurrencyModeOptions *HighConcurrencyModeOptions

	// Instance pool used to run this notebook.
	InstancePool *InstancePool

	// The list of abfs path of jars to be used in this session. Jars to include on the driver and executor classpaths.
	Jars []string

	// Mount points to be used in this session.
	MountPoints []MountPoint

	// The name of this session.
	Name *string

	// Number of executors to launch for this session. The minimum value is 1, and the maximum value has to be lower than the
	// instance pool maxNodeCount.
	NumExecutors *int32

	// The list of abfs path of python files to be used in this session. .zip, .egg, or .py files to place on the PYTHONPATH for
	// Python apps.
	PyFiles []string

	// A dictionary of Spark property key to their value.
	SparkProperties []SparkProperty
}

// SparkNotebookComputeDetails - Spark notebook compute details.
type SparkNotebookComputeDetails struct {
	// The high concurrency mode details.
	HighConcurrencyModeStatus *HighConcurrencyModeStatus

	// The livy id.
	LivyID *string

	// The spark notebook monitoring infomation.
	MonitoringInfo *SparkNotebookMonitoringInfo
}

// SparkNotebookJobInstanceProperties - Spark notebook job instance properties.
type SparkNotebookJobInstanceProperties struct {
	// REQUIRED; The execution engine for the job instance.
	Compute *ComputeType

	// REQUIRED; The details of spark notebook job instance.
	ComputeDetails *SparkNotebookComputeDetails

	// User defined exit value in notebook. Refer to this article [/fabric/data-engineering/notebook-utilities#exit-a-notebook]
	// for more details on how to set the notebook exit value.
	ExitValue *string
}

// GetJobInstanceProperties implements the JobInstancePropertiesClassification interface for type SparkNotebookJobInstanceProperties.
func (s *SparkNotebookJobInstanceProperties) GetJobInstanceProperties() *JobInstanceProperties {
	return &JobInstanceProperties{
		Compute:   s.Compute,
		ExitValue: s.ExitValue,
	}
}

// SparkNotebookMonitoringInfo - Spark notebook monitoring information.
type SparkNotebookMonitoringInfo struct {
	// Livy session details.
	ActivityDetails *SparkNotebookActivityDetails

	// Driver log url.
	DriverLogURL *string

	// Notebook execution snapshot url.
	ExecutionSnapshotURL *string

	// Spark job details url.
	SparkJobDetailsURL *string

	// Spark UI url.
	SparkUIURL *string
}

// SparkProperty - A Spark property key and its value.
type SparkProperty struct {
	// The Spark property key.
	Key *string

	// The Spark property value.
	Value *string
}

// UpdateNotebookDefinitionRequest - Update notebook public definition request payload.
type UpdateNotebookDefinitionRequest struct {
	// REQUIRED; Notebook public definition object. Refer to this article [/rest/api/fabric/articles/item-management/definitions/notebook-definition]
	// for more details on the structure of the Notebook definition.
	Definition *Definition
}

// UpdateNotebookRequest - Update notebook request.
type UpdateNotebookRequest struct {
	// The notebook description. Maximum length is 256 characters.
	Description *string

	// The notebook display name. The display name must follow naming rules according to item type.
	DisplayName *string
}

// UserPrincipal - Represents a Microsoft Entra user principal.
type UserPrincipal struct {
	// REQUIRED; The principal's ID.
	ID *string

	// REQUIRED; The type of the principal. Additional principal types may be added over time.
	Type *PrincipalType

	// READ-ONLY; The principal's display name.
	DisplayName *string

	// READ-ONLY; User principal specific details. Applicable when the principal type is User.
	UserDetails *UserPrincipalUserDetails
}

// GetPrincipal implements the PrincipalClassification interface for type UserPrincipal.
func (u *UserPrincipal) GetPrincipal() *Principal {
	return &Principal{
		DisplayName: u.DisplayName,
		ID:          u.ID,
		Type:        u.Type,
	}
}

// UserPrincipalUserDetails - User principal specific details. Applicable when the principal type is User.
type UserPrincipalUserDetails struct {
	// READ-ONLY; The user principal name.
	UserPrincipalName *string
}
